import { IResponse } from './assembly-model';

export const mockResponse: IResponse = {
  statusCode: 200,
  data: {
    assemblyHierarchy: {
      rootIds: ['DRIVE_ASSEMBLY', 'SHAFT_ASSEMBLY', 'BELLYPAN', 'LOWER-END_ASSEMBLY'],
      nodes: {
        'asm::CLASS_F4432WFMSS::CLASS_F4432WFMSS': {
          hierarchyId: 'asm::CLASS_F4432WFMSS::CLASS_F4432WFMSS',
          parentHierarchyId: '',
          assemblyName: 'Fine Material Washer',
          classRoot: 'CLASS_F4432WFMSS',
          parentClassCode: '',
          classCode: 'CLASS_F4432WFMSS',
          childIds: [],
          assemblyList: [],
          partsList: [
            {
              componentProductId: '03-03280',
              classCode: 'CLASS_03-03280',
              parentClassCode: 'CLASS_F4432WFMSS',
              useName_EN: 'BEARING',
              quantity: 1,
              classSource: 'pdm',
              flag: 'pagemap',
            },
            {
              componentProductId: '21-01056',
              classCode: 'CLASS_21-01056',
              parentClassCode: 'CLASS_F4432WFMSS',
              useName_EN: 'LOWER SEAL',
              quantity: 1,
              classSource: 'pdm',
              flag: 'pagemap',
            },
            {
              componentProductId: 'D--AP600-0607',
              classCode: 'CLASS_D--AP600-0607',
              parentClassCode: 'CLASS_F4432WFMSS',
              useName_EN: 'BEARING GUARD',
              quantity: 1,
              classSource: 'pdm',
              flag: 'pagemap',
            },
            {
              componentProductId: 'D-AP110-0220',
              classCode: 'CLASS_D-AP110-0220',
              parentClassCode: 'CLASS_F4432WFMSS',
              useName_EN: 'SLINGER',
              quantity: 1,
              classSource: 'pdm',
              flag: 'pagemap',
            },
            {
              componentProductId: 'D-AP400-0124',
              classCode: 'CLASS_D-AP400-0124',
              parentClassCode: 'CLASS_F4432WFMSS',
              useName_EN: 'GASKET',
              quantity: 1,
              classSource: 'pdm',
              flag: 'pagemap',
            },
            {
              componentProductId: 'D-AP400-0125',
              classCode: 'CLASS_D-AP400-0125',
              parentClassCode: 'CLASS_F4432WFMSS',
              useName_EN: 'PLATE',
              quantity: 1,
              classSource: 'pdm',
              flag: 'pagemap',
            },
            {
              componentProductId: 'D-AP400-0132',
              classCode: 'CLASS_D-AP400-0132',
              parentClassCode: 'CLASS_F4432WFMSS',
              useName_EN: 'WASHER',
              quantity: 8,
              classSource: 'pdm',
              flag: 'pagemap',
            },
            {
              componentProductId: 'D-AP500-0301',
              classCode: 'CLASS_D-AP500-0301',
              parentClassCode: 'CLASS_F4432WFMSS',
              useName_EN: 'RETAINER SEAL',
              quantity: 1,
              classSource: 'pdm',
              flag: 'pagemap',
            },
          ],
        },
        DRIVE_ASSEMBLY: {
          hierarchyId: 'DRIVE_ASSEMBLY',
          parentHierarchyId: '',
          assemblyName: 'DRIVE ASSEMBLY',
          classRoot: 'CLASS_F4432WFMSS',
          parentClassCode: 'CLASS_F4432WFMSS',
          classCode: 'CLASS_DRIVE_ASSEMBLY',
          childIds: [],
          assemblyList: [
            {
              extractedImgVersion: 8,
              selectedImageIndex: 0,
              productId: 'DRIVE_ASSEMBLY',
              mergedProductTable: [
                ['Sequence', 'Part Id', 'Description', 'Qty'],
                ['1', '04-00275', 'MOTOR', '1'],
                ['2', '03-05039', 'BEARING', '1'],
                ['3', 'D-AP600-0240', 'MOTOR MOUNT', '1'],
                ['4', '05-00525', 'GEAR REDUCER BUSHING', '1'],
                ['5', '05-00635', 'GEAR REDUCER', '1'],
                ['NS', 'D-AP600-0269', 'TORQUE ARM', '1'],
                ['6', 'D-AP600-0214', 'DRIVE GUARD BACK', '1'],
                ['7', '07-00089', 'V-BELT,B123', '2'],
                ['8', '06-00057', 'GEAR REDUCER SHEAVE', '1'],
                ['9', '02-00170', 'GEAR REDUCER SHEAVE BUSHING', '1'],
                ['10', '06-00043', 'MOTOR SHEAVE', '1'],
                ['11', '02-00106', 'MOTOR SHEAVE BUSHING', '1'],
                ['12', 'D-AP600-0213', 'DRIVE GUARD FRONT', '1'],
                ['13', 'D-AP600-0112', 'DRIVE GUARD MOUNT', '1'],
              ],
              assemblyId: '9cc415ce-c27a-4a0d-b8a8-671e03ad93f7',
              originalImgVersion: 194,
              classCodeInfo: {
                classRoot: 'CLASS_F4432WFMSS',
                classCode: 'CLASS_DRIVE_ASSEMBLY',
                parentClassCode: 'CLASS_F4432WFMSS',
              },
              prespectiveName: 'DRIVE_ASSEMBLY_7_1',
              pageId: '5bf1d038-4a50-4383-91e2-8dad5292134c',
              svgFileId: '665ee22d-0389-444c-8e82-b33abc1ff971',
              assemblyStatus: 'completed',
              svgFileVersion: 8,
              svgFileName: 'DRIVE_ASSEMBLY_DRIVE_ASSEMBLY_7_1.svg',
              svgHeader:
                '<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="3267" height="2567"><image width="3267" height="2567"  xlink:href="./DRIVE_ASSEMBLY_DRIVE_ASSEMBLY_7_1.png?domain=dkv2org202601221137&amp;workSpaceId=wsdkv1773509615749"></image>',
              userSave: false,
              pdsInfo: {
                serialNumber: '2552949',
                installDate: '09-2024',
                description: 'Fine Material Washer',
                modelNumber: 'F4432WFMSS',
              },
              extractedImgId: '27e01d23-8613-4bd1-bf42-007b6735dba7',
              originalImgId: '7bc5b06b-0df2-413d-92c1-5de962d50a05',
              extractedImageListByPage: [
                {
                  extractedImgVersion: 163,
                  productId: 'page-7_ORDER-1',
                  originalImgVersion: 194,
                  imageNameAsInPDF: 'Drive_Assembly',
                  svgFileId: null,
                  svgFileName: 'page-7_ORDER-1_svgfile.svg',
                  hotspotImgId: null,
                  svgHeader:
                    '<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="3267" height="2567"><image width="3267" height="2567" xlink:href="./page-7_ORDER-1_svgfile.png?"></image>',
                  secondaryExtractedImgId: null,
                  extractedImgId: '4e7de51e-9caf-4616-9cb5-b23e611832cb',
                  originalImgId: '7bc5b06b-0df2-413d-92c1-5de962d50a05',
                  drawingName: 'page-7_ORDER-1',
                  productDescription: null,
                  hotspotDetails: [
                    {
                      hotspotString: '2',
                      partId: '03-05039',
                      hotspotCoords: [
                        [189, 2446],
                        [261, 2523],
                      ],
                      partDescription: 'BEARING',
                      qty: '1',
                    },
                    {
                      hotspotString: '4',
                      partId: '05-00525',
                      hotspotCoords: [
                        [882, 2447],
                        [946, 2523],
                      ],
                      partDescription: 'GEAR REDUCER BUSHING',
                      qty: '1',
                    },
                    {
                      hotspotString: '1',
                      partId: '04-00275',
                      hotspotCoords: [
                        [242, 116],
                        [305, 193],
                      ],
                      partDescription: 'MOTOR',
                      qty: '1',
                    },
                    {
                      hotspotString: '5',
                      partId: '05-00635',
                      hotspotCoords: [
                        [1322, 2446],
                        [1389, 2523],
                      ],
                      partDescription: 'GEAR REDUCER',
                      qty: '1',
                    },
                    {
                      hotspotString: '8',
                      partId: '06-00057',
                      hotspotCoords: [
                        [2441, 2447],
                        [2507, 2522],
                      ],
                      partDescription: 'GEAR REDUCER SHEAVE',
                      qty: '1',
                    },
                    {
                      hotspotString: '9',
                      partId: '02-00170',
                      hotspotCoords: [
                        [2627, 2447],
                        [2694, 2523],
                      ],
                      partDescription: 'GEAR REDUCER SHEAVE BUSHING',
                      qty: '1',
                    },
                    {
                      hotspotString: '12',
                      partId: 'D-AP600-0213',
                      hotspotCoords: [
                        [3071, 2447],
                        [3161, 2522],
                      ],
                      partDescription: 'DRIVE GUARD FRONT',
                      qty: '1',
                    },
                    {
                      hotspotString: '3',
                      partId: 'D-AP600-0240',
                      hotspotCoords: [
                        [586, 2446],
                        [654, 2522],
                      ],
                      partDescription: 'MOTOR MOUNT',
                      qty: '1',
                    },
                    {
                      hotspotString: '10',
                      partId: '06-00043',
                      hotspotCoords: [
                        [2158, 118],
                        [2247, 190],
                      ],
                      partDescription: 'MOTOR SHEAVE',
                      qty: '1',
                    },
                    {
                      hotspotString: '11',
                      partId: '02-00106',
                      hotspotCoords: [
                        [2396, 118],
                        [2483, 191],
                      ],
                      partDescription: 'MOTOR SHEAVE BUSHING',
                      qty: '1',
                    },
                    {
                      hotspotString: '13',
                      partId: 'D-AP600-0112',
                      hotspotCoords: [
                        [909, 142],
                        [997, 219],
                      ],
                      partDescription: 'DRIVE GUARD MOUNT',
                      qty: '1',
                    },
                  ],
                  order: 1,
                  prespectiveName: null,
                },
              ],
              drawingName: 'DRIVE_ASSEMBLY_DRIVE_ASSEMBLY_7_1',
              hotspotDetails: [
                {
                  hotspotString: '2',
                  partId: '03-05039',
                  hotspotCoords: [
                    [189, 2446],
                    [261, 2523],
                  ],
                  partDescription: 'BEARING',
                  qty: '1',
                },
                {
                  hotspotString: '4',
                  partId: '05-00525',
                  hotspotCoords: [
                    [882, 2447],
                    [946, 2523],
                  ],
                  partDescription: 'GEAR REDUCER BUSHING',
                  qty: '1',
                },
                {
                  hotspotString: '1',
                  partId: '04-00275',
                  hotspotCoords: [
                    [242, 116],
                    [305, 193],
                  ],
                  partDescription: 'MOTOR',
                  qty: '1',
                },
                {
                  hotspotString: '5',
                  partId: '05-00635',
                  hotspotCoords: [
                    [1322, 2446],
                    [1389, 2523],
                  ],
                  partDescription: 'GEAR REDUCER',
                  qty: '1',
                },
                {
                  hotspotString: '8',
                  partId: '06-00057',
                  hotspotCoords: [
                    [2441, 2447],
                    [2507, 2522],
                  ],
                  partDescription: 'GEAR REDUCER SHEAVE',
                  qty: '1',
                },
                {
                  hotspotString: '9',
                  partId: '02-00170',
                  hotspotCoords: [
                    [2627, 2447],
                    [2694, 2523],
                  ],
                  partDescription: 'GEAR REDUCER SHEAVE BUSHING',
                  qty: '1',
                },
                {
                  hotspotString: '12',
                  partId: 'D-AP600-0213',
                  hotspotCoords: [
                    [3071, 2447],
                    [3161, 2522],
                  ],
                  partDescription: 'DRIVE GUARD FRONT',
                  qty: '1',
                },
                {
                  hotspotString: '3',
                  partId: 'D-AP600-0240',
                  hotspotCoords: [
                    [586, 2446],
                    [654, 2522],
                  ],
                  partDescription: 'MOTOR MOUNT',
                  qty: '1',
                },
                {
                  hotspotString: '10',
                  partId: '06-00043',
                  hotspotCoords: [
                    [2158, 118],
                    [2247, 190],
                  ],
                  partDescription: 'MOTOR SHEAVE',
                  qty: '1',
                },
                {
                  hotspotString: '11',
                  partId: '02-00106',
                  hotspotCoords: [
                    [2396, 118],
                    [2483, 191],
                  ],
                  partDescription: 'MOTOR SHEAVE BUSHING',
                  qty: '1',
                },
                {
                  hotspotString: '13',
                  partId: 'D-AP600-0112',
                  hotspotCoords: [
                    [909, 142],
                    [997, 219],
                  ],
                  partDescription: 'DRIVE GUARD MOUNT',
                  qty: '1',
                },
              ],
              linkedPageProductTable: {
                'page-7': {
                  tables: [
                    {
                      tableNameAsInPDF: 'Drive_Assembly',
                      isAccepted: true,
                      tableData: [
                        ['Sequence', 'Part Id', 'Description', 'Qty'],
                        ['1', '04-00275', 'MOTOR', '1'],
                        ['2', '03-05039', 'BEARING', '1'],
                        ['3', 'D-AP600-0240', 'MOTOR MOUNT', '1'],
                        ['4', '05-00525', 'GEAR REDUCER BUSHING', '1'],
                        ['5', '05-00635', 'GEAR REDUCER', '1'],
                        ['NS', 'D-AP600-0269', 'TORQUE ARM', '1'],
                        ['6', 'D-AP600-0214', 'DRIVE GUARD BACK', '1'],
                        ['7', '07-00089', 'V-BELT,B123', '2'],
                        ['8', '06-00057', 'GEAR REDUCER SHEAVE', '1'],
                        ['9', '02-00170', 'GEAR REDUCER SHEAVE BUSHING', '1'],
                        ['10', '06-00043', 'MOTOR SHEAVE', '1'],
                        ['11', '02-00106', 'MOTOR SHEAVE BUSHING', '1'],
                        ['12', 'D-AP600-0213', 'DRIVE GUARD FRONT', '1'],
                        ['13', 'D-AP600-0112', 'DRIVE GUARD MOUNT', '1'],
                      ],
                      tableName: 'Table No. 1',
                      order: 1,
                    },
                  ],
                  pageKey: 'page-7',
                  pageId: '5bf1d038-4a50-4383-91e2-8dad5292134c',
                  pageName: 'Page No. 7',
                },
              },
              status: 'completed',
            },
          ],
          partsList: [
            {
              componentProductId: '04-00275',
              classCode: 'CLASS_04-00275',
              parentClassCode: 'CLASS_DRIVE_ASSEMBLY',
              useName_EN: 'MOTOR',
              quantity: 1,
              classSource: 'pdm',
              flag: 'pagemap',
            },
            {
              componentProductId: '03-05039',
              classCode: 'CLASS_03-05039',
              parentClassCode: 'CLASS_DRIVE_ASSEMBLY',
              useName_EN: 'BEARING',
              quantity: 1,
              classSource: 'pdm',
              flag: 'pagemap',
            },
            {
              componentProductId: 'D-AP600-0240',
              classCode: 'CLASS_D-AP600-0240',
              parentClassCode: 'CLASS_DRIVE_ASSEMBLY',
              useName_EN: 'MOTOR MOUNT',
              quantity: 1,
              classSource: 'pdm',
              flag: 'pagemap',
            },
            {
              componentProductId: '05-00525',
              classCode: 'CLASS_05-00525',
              parentClassCode: 'CLASS_DRIVE_ASSEMBLY',
              useName_EN: 'GEAR REDUCER BUSHING',
              quantity: 1,
              classSource: 'pdm',
              flag: 'pagemap',
            },
            {
              componentProductId: '05-00635',
              classCode: 'CLASS_05-00635',
              parentClassCode: 'CLASS_DRIVE_ASSEMBLY',
              useName_EN: 'GEAR REDUCER',
              quantity: 1,
              classSource: 'pdm',
              flag: 'pagemap',
            },
            {
              componentProductId: 'D-AP600-0269',
              classCode: 'CLASS_D-AP600-0269',
              parentClassCode: 'CLASS_DRIVE_ASSEMBLY',
              useName_EN: 'TORQUE ARM',
              quantity: 1,
              classSource: 'pdm',
              flag: 'pagemap',
            },
            {
              componentProductId: 'D-AP600-0214',
              classCode: 'CLASS_D-AP600-0214',
              parentClassCode: 'CLASS_DRIVE_ASSEMBLY',
              useName_EN: 'DRIVE GUARD BACK',
              quantity: 1,
              classSource: 'pdm',
              flag: 'pagemap',
            },
            {
              componentProductId: '07-00089',
              classCode: 'CLASS_07-00089',
              parentClassCode: 'CLASS_DRIVE_ASSEMBLY',
              useName_EN: 'V-BELT,B123',
              quantity: 2,
              classSource: 'pdm',
              flag: 'pagemap',
            },
            {
              componentProductId: '06-00057',
              classCode: 'CLASS_06-00057',
              parentClassCode: 'CLASS_DRIVE_ASSEMBLY',
              useName_EN: 'GEAR REDUCER SHEAVE',
              quantity: 1,
              classSource: 'pdm',
              flag: 'pagemap',
            },
            {
              componentProductId: '02-00170',
              classCode: 'CLASS_02-00170',
              parentClassCode: 'CLASS_DRIVE_ASSEMBLY',
              useName_EN: 'GEAR REDUCER SHEAVE BUSHING',
              quantity: 1,
              classSource: 'pdm',
              flag: 'pagemap',
            },
            {
              componentProductId: '06-00043',
              classCode: 'CLASS_06-00043',
              parentClassCode: 'CLASS_DRIVE_ASSEMBLY',
              useName_EN: 'MOTOR SHEAVE',
              quantity: 1,
              classSource: 'pdm',
              flag: 'pagemap',
            },
            {
              componentProductId: '02-00106',
              classCode: 'CLASS_02-00106',
              parentClassCode: 'CLASS_DRIVE_ASSEMBLY',
              useName_EN: 'MOTOR SHEAVE BUSHING',
              quantity: 1,
              classSource: 'pdm',
              flag: 'pagemap',
            },
            {
              componentProductId: 'D-AP600-0213',
              classCode: 'CLASS_D-AP600-0213',
              parentClassCode: 'CLASS_DRIVE_ASSEMBLY',
              useName_EN: 'DRIVE GUARD FRONT',
              quantity: 1,
              classSource: 'pdm',
              flag: 'pagemap',
            },
            {
              componentProductId: 'D-AP600-0112',
              classCode: 'CLASS_D-AP600-0112',
              parentClassCode: 'CLASS_DRIVE_ASSEMBLY',
              useName_EN: 'DRIVE GUARD MOUNT',
              quantity: 1,
              classSource: 'pdm',
              flag: 'pagemap',
            },
          ],
        },
        SHAFT_ASSEMBLY: {
          hierarchyId: 'SHAFT_ASSEMBLY',
          parentHierarchyId: '',
          assemblyName: 'SHAFT ASSEMBLY',
          classRoot: 'CLASS_F4432WFMSS',
          parentClassCode: 'CLASS_F4432WFMSS',
          classCode: 'CLASS_SHAFT_ASSEMBLY',
          childIds: [],
          assemblyList: [
            {
              extractedImgVersion: 8,
              selectedImageIndex: 0,
              productId: 'SHAFT_ASSEMBLY',
              mergedProductTable: [
                ['Sequence', 'Part Id', 'Description', 'Qty'],
                ['1', 'D-AP105-4410', 'DRIVE SHAFT', '1'],
                ['2', 'D-AP105-4400', 'STUB SHAFT WITH SLEEVE', '1'],
                ['3', '13-10946', 'BLT,HEX,7/8-14X3-1/2,GR8,PLNHEX,CAP,SCREW', '24'],
                ['4', '13-10973', 'NUT,HEX,7/8-14,GR8,PLNHEX,NUT', '24'],
                ['5', '13-00203', 'WSR,LCK,7/8', '24'],
                ['6', 'D-AP130-61B3', 'SCREW SHAFT WITH FLIGHTS', '1'],
                ['7', '15-00890', 'SHOE,A532/NI-HARD,44",RH,GREYSTONE', '198'],
              ],
              assemblyId: '143155d4-31d9-4f3e-8e7b-e1e0f0f9cced',
              originalImgVersion: 194,
              classCodeInfo: {
                classRoot: 'CLASS_F4432WFMSS',
                classCode: 'CLASS_SHAFT_ASSEMBLY',
                parentClassCode: 'CLASS_F4432WFMSS',
              },
              prespectiveName: 'SHAFT_ASSEMBLY_8_1',
              pageId: 'd30cbf51-8a4c-48d2-822d-487c68a9e3d2',
              svgFileId: '95914f70-835d-486d-afb1-bf455c3435f5',
              assemblyStatus: 'completed',
              svgFileVersion: 8,
              svgFileName: 'SHAFT_ASSEMBLY_SHAFT_ASSEMBLY_8_1.svg',
              svgHeader:
                '<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="3841" height="2327"><image width="3841" height="2327"  xlink:href="./SHAFT_ASSEMBLY_SHAFT_ASSEMBLY_8_1.png?domain=dkv2org202601221137&amp;workSpaceId=wsdkv1773509615749"></image>',
              userSave: false,
              pdsInfo: {
                serialNumber: '2552949',
                installDate: '09-2024',
                description: 'Fine Material Washer',
                modelNumber: 'F4432WFMSS',
              },
              extractedImgId: '5c947a42-e88a-43ef-b63e-47a59fa02800',
              originalImgId: 'bd0d53d9-8fdf-40a8-b0e2-d2320da2d896',
              extractedImageListByPage: [
                {
                  extractedImgVersion: 98,
                  productId: 'page-8_ORDER-1',
                  originalImgVersion: 194,
                  imageNameAsInPDF: 'Shaft_Assembly',
                  svgFileId: null,
                  svgFileName: 'page-8_ORDER-1_svgfile.svg',
                  hotspotImgId: null,
                  svgHeader:
                    '<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="3841" height="2327"><image width="3841" height="2327" xlink:href="./page-8_ORDER-1_svgfile.png?"></image>',
                  secondaryExtractedImgId: null,
                  extractedImgId: 'f5d7233c-0fcb-48e7-a725-606ce9583300',
                  originalImgId: 'bd0d53d9-8fdf-40a8-b0e2-d2320da2d896',
                  drawingName: 'page-8_ORDER-1',
                  productDescription: null,
                  hotspotDetails: [
                    {
                      hotspotString: '1',
                      partId: 'D-AP105-4410',
                      hotspotCoords: [
                        [3724, 608],
                        [3787, 685],
                      ],
                      partDescription: 'DRIVE SHAFT',
                      qty: '1',
                    },
                    {
                      hotspotString: '7',
                      partId: '15-00890',
                      hotspotCoords: [
                        [797, 910],
                        [865, 986],
                      ],
                      partDescription: 'SHOE,A532/NI-HARD,44",RH,GREYSTONE',
                      qty: '198',
                    },
                    {
                      hotspotString: '2',
                      partId: 'D-AP105-4400',
                      hotspotCoords: [
                        [57, 1611],
                        [123, 1688],
                      ],
                      partDescription: 'STUB SHAFT WITH SLEEVE',
                      qty: '1',
                    },
                    {
                      hotspotString: '5',
                      partId: '13-00203',
                      hotspotCoords: [
                        [492, 1356],
                        [561, 1435],
                      ],
                      partDescription: 'WSR,LCK,7/8',
                      qty: '24',
                    },
                    {
                      hotspotString: '4',
                      partId: '13-10973',
                      hotspotCoords: [
                        [383, 1402],
                        [447, 1480],
                      ],
                      partDescription: 'NUT,HEX,7/8-14,GR8,PLNHEX,NUT',
                      qty: '24',
                    },
                    {
                      hotspotString: '3',
                      partId: '13-10946',
                      hotspotCoords: [
                        [270, 1450],
                        [332, 1527],
                      ],
                      partDescription: 'BLT,HEX,7/8-14X3-1/2,GR8,PLNHEX,CAP,SCREW',
                      qty: '24',
                    },
                  ],
                  order: 1,
                  prespectiveName: null,
                },
              ],
              drawingName: 'SHAFT_ASSEMBLY_SHAFT_ASSEMBLY_8_1',
              hotspotDetails: [
                {
                  hotspotString: '1',
                  partId: 'D-AP105-4410',
                  hotspotCoords: [
                    [3724, 608],
                    [3787, 685],
                  ],
                  partDescription: 'DRIVE SHAFT',
                  qty: '1',
                },
                {
                  hotspotString: '7',
                  partId: '15-00890',
                  hotspotCoords: [
                    [797, 910],
                    [865, 986],
                  ],
                  partDescription: 'SHOE,A532/NI-HARD,44",RH,GREYSTONE',
                  qty: '198',
                },
                {
                  hotspotString: '2',
                  partId: 'D-AP105-4400',
                  hotspotCoords: [
                    [57, 1611],
                    [123, 1688],
                  ],
                  partDescription: 'STUB SHAFT WITH SLEEVE',
                  qty: '1',
                },
                {
                  hotspotString: '5',
                  partId: '13-00203',
                  hotspotCoords: [
                    [492, 1356],
                    [561, 1435],
                  ],
                  partDescription: 'WSR,LCK,7/8',
                  qty: '24',
                },
                {
                  hotspotString: '4',
                  partId: '13-10973',
                  hotspotCoords: [
                    [383, 1402],
                    [447, 1480],
                  ],
                  partDescription: 'NUT,HEX,7/8-14,GR8,PLNHEX,NUT',
                  qty: '24',
                },
                {
                  hotspotString: '3',
                  partId: '13-10946',
                  hotspotCoords: [
                    [270, 1450],
                    [332, 1527],
                  ],
                  partDescription: 'BLT,HEX,7/8-14X3-1/2,GR8,PLNHEX,CAP,SCREW',
                  qty: '24',
                },
              ],
              linkedPageProductTable: {
                'page-8': {
                  tables: [
                    {
                      tableNameAsInPDF: 'Shaft_Assembly',
                      isAccepted: true,
                      tableData: [
                        ['Sequence', 'Part Id', 'Description', 'Qty'],
                        ['1', 'D-AP105-4410', 'DRIVE SHAFT', '1'],
                        ['2', 'D-AP105-4400', 'STUB SHAFT WITH SLEEVE', '1'],
                        ['3', '13-10946', 'BLT,HEX,7/8-14X3-1/2,GR8,PLNHEX,CAP,SCREW', '24'],
                        ['4', '13-10973', 'NUT,HEX,7/8-14,GR8,PLNHEX,NUT', '24'],
                        ['5', '13-00203', 'WSR,LCK,7/8', '24'],
                        ['6', 'D-AP130-61B3', 'SCREW SHAFT WITH FLIGHTS', '1'],
                        ['7', '15-00890', 'SHOE,A532/NI-HARD,44",RH,GREYSTONE', '198'],
                      ],
                      tableName: 'Table No. 1',
                      order: 1,
                    },
                  ],
                  pageKey: 'page-8',
                  pageId: 'd30cbf51-8a4c-48d2-822d-487c68a9e3d2',
                  pageName: 'Page No. 8',
                },
              },
              status: 'completed',
            },
          ],
          partsList: [
            {
              componentProductId: 'D-AP105-4410',
              classCode: 'CLASS_D-AP105-4410',
              parentClassCode: 'CLASS_SHAFT_ASSEMBLY',
              useName_EN: 'DRIVE SHAFT',
              quantity: 1,
              classSource: 'pdm',
              flag: 'pagemap',
            },
            {
              componentProductId: 'D-AP105-4400',
              classCode: 'CLASS_D-AP105-4400',
              parentClassCode: 'CLASS_SHAFT_ASSEMBLY',
              useName_EN: 'STUB SHAFT WITH SLEEVE',
              quantity: 1,
              classSource: 'pdm',
              flag: 'pagemap',
            },
            {
              componentProductId: '13-10946',
              classCode: 'CLASS_13-10946',
              parentClassCode: 'CLASS_SHAFT_ASSEMBLY',
              useName_EN: 'BLT,HEX,7/8-14X3-1/2,GR8,PLNHEX,CAP,SCREW',
              quantity: 24,
              classSource: 'pdm',
              flag: 'pagemap',
            },
            {
              componentProductId: '13-10973',
              classCode: 'CLASS_13-10973',
              parentClassCode: 'CLASS_SHAFT_ASSEMBLY',
              useName_EN: 'NUT,HEX,7/8-14,GR8,PLNHEX,NUT',
              quantity: 24,
              classSource: 'pdm',
              flag: 'pagemap',
            },
            {
              componentProductId: '13-00203',
              classCode: 'CLASS_13-00203',
              parentClassCode: 'CLASS_SHAFT_ASSEMBLY',
              useName_EN: 'WSR,LCK,7/8',
              quantity: 24,
              classSource: 'pdm',
              flag: 'pagemap',
            },
            {
              componentProductId: 'D-AP130-61B3',
              classCode: 'CLASS_D-AP130-61B3',
              parentClassCode: 'CLASS_SHAFT_ASSEMBLY',
              useName_EN: 'SCREW SHAFT WITH FLIGHTS',
              quantity: 1,
              classSource: 'pdm',
              flag: 'pagemap',
            },
            {
              componentProductId: '15-00890',
              classCode: 'CLASS_15-00890',
              parentClassCode: 'CLASS_SHAFT_ASSEMBLY',
              useName_EN: 'SHOE,A532/NI-HARD,44",RH,GREYSTONE',
              quantity: 198,
              classSource: 'pdm',
              flag: 'pagemap',
            },
          ],
        },
        BELLYPAN: {
          hierarchyId: 'BELLYPAN',
          parentHierarchyId: '',
          assemblyName: 'BELLYPAN',
          classRoot: 'CLASS_F4432WFMSS',
          parentClassCode: 'CLASS_F4432WFMSS',
          classCode: 'CLASS_BELLYPAN',
          childIds: [],
          assemblyList: [
            {
              extractedImgVersion: 8,
              selectedImageIndex: 0,
              productId: 'BELLYPAN',
              mergedProductTable: [
                ['Sequence', 'Part Id', 'Description', 'Qty'],
                ['1', 'D-AP200-4410', 'BELLYPAN WITH HOLES126" LG', '1'],
                ['2', 'D-AP200-4411', 'BELLYPAN NO HOLES 113"LG', '1'],
                ['3', 'D-AP200-4412', 'BELLYPAN NO HOLES 126" LG', '24'],
              ],
              assemblyId: '329c06b5-b814-43b6-9edf-fc380fcf03bd',
              originalImgVersion: 193,
              classCodeInfo: {
                classRoot: 'CLASS_F4432WFMSS',
                classCode: 'CLASS_BELLYPAN',
                parentClassCode: 'CLASS_F4432WFMSS',
              },
              prespectiveName: 'BELLYPAN_10_1',
              pageId: '2978925c-00c1-4470-b358-7e8175cb5249',
              svgFileId: '4edfbe73-9b7e-4d10-9aa6-df9ced59d063',
              assemblyStatus: 'completed',
              svgFileVersion: 8,
              svgFileName: 'BELLYPAN_BELLYPAN_10_1.svg',
              svgHeader:
                '<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="3573" height="1872"><image width="3573" height="1872"  xlink:href="./BELLYPAN_BELLYPAN_10_1.png?domain=dkv2org202601221137&amp;workSpaceId=wsdkv1773509615749"></image>',
              userSave: false,
              pdsInfo: {
                serialNumber: '2552949',
                installDate: '09-2024',
                description: 'Fine Material Washer',
                modelNumber: 'F4432WFMSS',
              },
              extractedImgId: '62b38b81-cf01-4b65-9e2a-840fe5dcd55a',
              originalImgId: '62ca1902-e61d-4b6c-9803-7362957abe0e',
              extractedImageListByPage: [
                {
                  extractedImgVersion: 171,
                  productId: 'page-10_ORDER-1',
                  originalImgVersion: 193,
                  imageNameAsInPDF: 'Bellypan',
                  svgFileId: null,
                  svgFileName: 'page-10_ORDER-1_svgfile.svg',
                  hotspotImgId: null,
                  svgHeader:
                    '<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="3573" height="1872"><image width="3573" height="1872" xlink:href="./page-10_ORDER-1_svgfile.png?"></image>',
                  secondaryExtractedImgId: null,
                  extractedImgId: '93e4bc39-eabc-4835-9665-8f08e06bff88',
                  originalImgId: '62ca1902-e61d-4b6c-9803-7362957abe0e',
                  drawingName: 'page-10_ORDER-1',
                  productDescription: null,
                  hotspotDetails: [
                    {
                      hotspotString: '1',
                      partId: 'D-AP200-4410',
                      hotspotCoords: [
                        [435, 781],
                        [497, 856],
                      ],
                      partDescription: 'BELLYPAN WITH HOLES126" LG',
                      qty: '1',
                    },
                    {
                      hotspotString: '2',
                      partId: 'D-AP200-4411',
                      hotspotCoords: [
                        [1321, 440],
                        [1390, 514],
                      ],
                      partDescription: 'BELLYPAN NO HOLES 113"LG',
                      qty: '1',
                    },
                    {
                      hotspotString: '3',
                      partId: 'D-AP200-4412',
                      hotspotCoords: [
                        [2204, 46],
                        [2268, 122],
                      ],
                      partDescription: 'BELLYPAN NO HOLES 126" LG',
                      qty: '24',
                    },
                  ],
                  order: 1,
                  prespectiveName: null,
                },
              ],
              drawingName: 'BELLYPAN_BELLYPAN_10_1',
              hotspotDetails: [
                {
                  hotspotString: '1',
                  partId: 'D-AP200-4410',
                  hotspotCoords: [
                    [435, 781],
                    [497, 856],
                  ],
                  partDescription: 'BELLYPAN WITH HOLES126" LG',
                  qty: '1',
                },
                {
                  hotspotString: '2',
                  partId: 'D-AP200-4411',
                  hotspotCoords: [
                    [1321, 440],
                    [1390, 514],
                  ],
                  partDescription: 'BELLYPAN NO HOLES 113"LG',
                  qty: '1',
                },
                {
                  hotspotString: '3',
                  partId: 'D-AP200-4412',
                  hotspotCoords: [
                    [2204, 46],
                    [2268, 122],
                  ],
                  partDescription: 'BELLYPAN NO HOLES 126" LG',
                  qty: '24',
                },
              ],
              linkedPageProductTable: {
                'page-10': {
                  tables: [
                    {
                      tableNameAsInPDF: '3_Upper',
                      isAccepted: true,
                      tableData: [
                        ['Sequence', 'Part Id', 'Description', 'Qty'],
                        ['1', 'D-AP200-4410', 'BELLYPAN WITH HOLES126" LG', '1'],
                        ['2', 'D-AP200-4411', 'BELLYPAN NO HOLES 113"LG', '1'],
                        ['3', 'D-AP200-4412', 'BELLYPAN NO HOLES 126" LG', '24'],
                      ],
                      tableName: 'Table No. 1',
                      order: 1,
                    },
                  ],
                  pageKey: 'page-10',
                  pageId: '2978925c-00c1-4470-b358-7e8175cb5249',
                  pageName: 'Page No. 10',
                },
              },
              status: 'completed',
            },
          ],
          partsList: [
            {
              componentProductId: 'D-AP200-4410',
              classCode: 'CLASS_D-AP200-4410',
              parentClassCode: 'CLASS_BELLYPAN',
              useName_EN: 'BELLYPAN WITH HOLES126" LG',
              quantity: 1,
              classSource: 'pdm',
              flag: 'pagemap',
            },
            {
              componentProductId: 'D-AP200-4411',
              classCode: 'CLASS_D-AP200-4411',
              parentClassCode: 'CLASS_BELLYPAN',
              useName_EN: 'BELLYPAN NO HOLES 113"LG',
              quantity: 1,
              classSource: 'pdm',
              flag: 'pagemap',
            },
            {
              componentProductId: 'D-AP200-4412',
              classCode: 'CLASS_D-AP200-4412',
              parentClassCode: 'CLASS_BELLYPAN',
              useName_EN: 'BELLYPAN NO HOLES 126" LG',
              quantity: 24,
              classSource: 'pdm',
              flag: 'pagemap',
            },
          ],
        },
        'LOWER-END_ASSEMBLY': {
          hierarchyId: 'LOWER-END_ASSEMBLY',
          parentHierarchyId: '',
          assemblyName: 'LOWER-END ASSEMBLY',
          classRoot: 'CLASS_F4432WFMSS',
          parentClassCode: 'CLASS_F4432WFMSS',
          classCode: 'CLASS_LOWER-END_ASSEMBLY',
          childIds: [],
          assemblyList: [
            {
              extractedImgVersion: 6,
              selectedImageIndex: 0,
              productId: 'LOWER-END_ASSEMBLY',
              mergedProductTable: [
                ['Sequence', 'Part Id', 'Description', 'Qty'],
                ['1', '03-03280', 'BEARING', '1'],
                ['2', 'D-AP110-0220', 'SLINGER', '1'],
                ['3', 'D-AP500-0301', 'RETAINER SEAL', '1'],
                ['4', '21-01056', 'LOWER SEAL', '1'],
                ['5', 'D-AP400-0132', 'WASHER', '8'],
                ['6', 'D-AP400-0125', 'PLATE', '1'],
                ['7', 'D-AP400-0124', 'GASKET', '1'],
                ['N/S', 'D--AP600-0607', 'BEARING GUARD', '1'],
              ],
              assemblyId: 'f499e244-1d6e-4a4c-ab63-b3a5cd78a898',
              originalImgVersion: 194,
              classCodeInfo: {
                classRoot: 'CLASS_F4432WFMSS',
                classCode: 'CLASS_LOWER-END_ASSEMBLY',
                parentClassCode: 'CLASS_F4432WFMSS',
              },
              prespectiveName: 'LOWER-END_ASSEMBLY_11_1',
              pageId: '385c5602-8a2c-4c16-bef2-828a8ae12425',
              svgFileId: 'e4ab13c5-11f0-4d8a-aaa4-9fddb5c05ad0',
              assemblyStatus: 'completed',
              svgFileVersion: 6,
              svgFileName: 'LOWER-END_ASSEMBLY_LOWER-END_ASSEMBLY_11_1.svg',
              svgHeader:
                '<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="2878" height="2183"><image width="2878" height="2183"  xlink:href="./LOWER-END_ASSEMBLY_LOWER-END_ASSEMBLY_11_1.png?domain=dkv2org202601221137&amp;workSpaceId=wsdkv1773509615749"></image>',
              userSave: false,
              pdsInfo: {
                serialNumber: '2552949',
                installDate: '09-2024',
                description: 'Fine Material Washer',
                modelNumber: 'F4432WFMSS',
              },
              extractedImgId: 'e4148542-7a1d-4e13-a42b-50e8b121ade3',
              originalImgId: '611257b7-7bec-4295-88c3-87b7b20208a3',
              extractedImageListByPage: [
                {
                  extractedImgVersion: 130,
                  productId: 'page-11_ORDER-1',
                  originalImgVersion: 194,
                  imageNameAsInPDF: 'Lower-End_Assembly',
                  svgFileId: null,
                  svgFileName: 'page-11_ORDER-1_svgfile.svg',
                  hotspotImgId: null,
                  svgHeader:
                    '<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="2878" height="2183"><image width="2878" height="2183" xlink:href="./page-11_ORDER-1_svgfile.png?"></image>',
                  secondaryExtractedImgId: null,
                  extractedImgId: 'f5df3f4c-9147-4a21-8667-4dd6554fcf8d',
                  originalImgId: '611257b7-7bec-4295-88c3-87b7b20208a3',
                  drawingName: 'page-11_ORDER-1',
                  productDescription: null,
                  hotspotDetails: [
                    {
                      hotspotString: '4',
                      partId: '21-01056',
                      hotspotCoords: [
                        [1242, 2062],
                        [1307, 2139],
                      ],
                      partDescription: 'LOWER SEAL',
                      qty: '1',
                    },
                    {
                      hotspotString: '1',
                      partId: '03-03280',
                      hotspotCoords: [
                        [418, 2062],
                        [479, 2136],
                      ],
                      partDescription: 'BEARING',
                      qty: '1',
                    },
                    {
                      hotspotString: '5',
                      partId: 'D-AP400-0132',
                      hotspotCoords: [
                        [1712, 2061],
                        [1778, 2138],
                      ],
                      partDescription: 'WASHER',
                      qty: '8',
                    },
                    {
                      hotspotString: '7',
                      partId: 'D-AP400-0124',
                      hotspotCoords: [
                        [2578, 2060],
                        [2643, 2138],
                      ],
                      partDescription: 'GASKET',
                      qty: '1',
                    },
                    {
                      hotspotString: '3',
                      partId: 'D-AP500-0301',
                      hotspotCoords: [
                        [967, 2061],
                        [1034, 2138],
                      ],
                      partDescription: 'RETAINER SEAL',
                      qty: '1',
                    },
                    {
                      hotspotString: '2',
                      partId: 'D-AP110-0220',
                      hotspotCoords: [
                        [646, 2062],
                        [716, 2138],
                      ],
                      partDescription: 'SLINGER',
                      qty: '1',
                    },
                  ],
                  order: 1,
                  prespectiveName: null,
                },
              ],
              drawingName: 'LOWER-END_ASSEMBLY_LOWER-END_ASSEMBLY_11_1',
              hotspotDetails: [
                {
                  hotspotString: '4',
                  partId: '21-01056',
                  hotspotCoords: [
                    [1242, 2062],
                    [1307, 2139],
                  ],
                  partDescription: 'LOWER SEAL',
                  qty: '1',
                },
                {
                  hotspotString: '1',
                  partId: '03-03280',
                  hotspotCoords: [
                    [418, 2062],
                    [479, 2136],
                  ],
                  partDescription: 'BEARING',
                  qty: '1',
                },
                {
                  hotspotString: '5',
                  partId: 'D-AP400-0132',
                  hotspotCoords: [
                    [1712, 2061],
                    [1778, 2138],
                  ],
                  partDescription: 'WASHER',
                  qty: '8',
                },
                {
                  hotspotString: '7',
                  partId: 'D-AP400-0124',
                  hotspotCoords: [
                    [2578, 2060],
                    [2643, 2138],
                  ],
                  partDescription: 'GASKET',
                  qty: '1',
                },
                {
                  hotspotString: '3',
                  partId: 'D-AP500-0301',
                  hotspotCoords: [
                    [967, 2061],
                    [1034, 2138],
                  ],
                  partDescription: 'RETAINER SEAL',
                  qty: '1',
                },
                {
                  hotspotString: '2',
                  partId: 'D-AP110-0220',
                  hotspotCoords: [
                    [646, 2062],
                    [716, 2138],
                  ],
                  partDescription: 'SLINGER',
                  qty: '1',
                },
              ],
              linkedPageProductTable: {
                'page-11': {
                  tables: [
                    {
                      tableNameAsInPDF: 'Lower-End_Assembly',
                      isAccepted: true,
                      tableData: [
                        ['Sequence', 'Part Id', 'Description', 'Qty'],
                        ['1', '03-03280', 'BEARING', '1'],
                        ['2', 'D-AP110-0220', 'SLINGER', '1'],
                        ['3', 'D-AP500-0301', 'RETAINER SEAL', '1'],
                        ['4', '21-01056', 'LOWER SEAL', '1'],
                        ['5', 'D-AP400-0132', 'WASHER', '8'],
                        ['6', 'D-AP400-0125', 'PLATE', '1'],
                        ['7', 'D-AP400-0124', 'GASKET', '1'],
                        ['N/S', 'D--AP600-0607', 'BEARING GUARD', '1'],
                      ],
                      tableName: 'Table No. 1',
                      order: 1,
                    },
                  ],
                  pageKey: 'page-11',
                  pageId: '385c5602-8a2c-4c16-bef2-828a8ae12425',
                  pageName: 'Page No. 11',
                },
              },
              status: 'completed',
            },
          ],
          partsList: [
            {
              componentProductId: '03-03280',
              classCode: 'CLASS_03-03280',
              parentClassCode: 'CLASS_LOWER-END_ASSEMBLY',
              useName_EN: 'BEARING',
              quantity: 1,
              classSource: 'pdm',
              flag: 'pagemap',
            },
            {
              componentProductId: 'D-AP110-0220',
              classCode: 'CLASS_D-AP110-0220',
              parentClassCode: 'CLASS_LOWER-END_ASSEMBLY',
              useName_EN: 'SLINGER',
              quantity: 1,
              classSource: 'pdm',
              flag: 'pagemap',
            },
            {
              componentProductId: 'D-AP500-0301',
              classCode: 'CLASS_D-AP500-0301',
              parentClassCode: 'CLASS_LOWER-END_ASSEMBLY',
              useName_EN: 'RETAINER SEAL',
              quantity: 1,
              classSource: 'pdm',
              flag: 'pagemap',
            },
            {
              componentProductId: '21-01056',
              classCode: 'CLASS_21-01056',
              parentClassCode: 'CLASS_LOWER-END_ASSEMBLY',
              useName_EN: 'LOWER SEAL',
              quantity: 1,
              classSource: 'pdm',
              flag: 'pagemap',
            },
            {
              componentProductId: 'D-AP400-0132',
              classCode: 'CLASS_D-AP400-0132',
              parentClassCode: 'CLASS_LOWER-END_ASSEMBLY',
              useName_EN: 'WASHER',
              quantity: 8,
              classSource: 'pdm',
              flag: 'pagemap',
            },
            {
              componentProductId: 'D-AP400-0125',
              classCode: 'CLASS_D-AP400-0125',
              parentClassCode: 'CLASS_LOWER-END_ASSEMBLY',
              useName_EN: 'PLATE',
              quantity: 1,
              classSource: 'pdm',
              flag: 'pagemap',
            },
            {
              componentProductId: 'D-AP400-0124',
              classCode: 'CLASS_D-AP400-0124',
              parentClassCode: 'CLASS_LOWER-END_ASSEMBLY',
              useName_EN: 'GASKET',
              quantity: 1,
              classSource: 'pdm',
              flag: 'pagemap',
            },
            {
              componentProductId: 'D--AP600-0607',
              classCode: 'CLASS_D--AP600-0607',
              parentClassCode: 'CLASS_LOWER-END_ASSEMBLY',
              useName_EN: 'BEARING GUARD',
              quantity: 1,
              classSource: 'pdm',
              flag: 'pagemap',
            },
          ],
        },
      },
      classRoot: 'CLASS_F4432WFMSS',
      imageList: [
        {
          drawingName: 'page-6_ORDER-1',
          imageNameAsInPDF: 'Washer_Overview',
          productId: 'page-6_ORDER-1',
          productDescription: null,
          extractedImgId: '0b30ab2e-634c-4966-9621-9509f6b8fb4d',
          extractedImgVersion: 171,
          pageNo: 'page-6',
          type: 'image',
          prespectiveName: '',
          pageId: '0120193c-7762-4d70-8b5b-411fb3d4353f',
          hotspotDetails: [
            {
              hotspotString: '2',
              hotspotCoords: [
                [1614, 918],
                [1686, 994],
              ],
              partId: null,
              partDescription: null,
              qty: 0,
            },
            {
              hotspotString: '3',
              hotspotCoords: [
                [402, 2538],
                [468, 2615],
              ],
              partId: null,
              partDescription: null,
              qty: 0,
            },
            {
              hotspotString: '4',
              hotspotCoords: [
                [1345, 1147],
                [1413, 1225],
              ],
              partId: null,
              partDescription: null,
              qty: 0,
            },
          ],
          svgHeader:
            '<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="3019" height="2957"><image width="3019" height="2957" xlink:href="./page-6_ORDER-1_svgfile.png?"></image>',
          svgFileName: 'page-6_ORDER-1_svgfile.svg',
          svgFileId: null,
          assemblyIdRef: '',
        },
        {
          drawingName: 'page-9_ORDER-1',
          imageNameAsInPDF: 'Flights_and_Gussets',
          productId: 'page-9_ORDER-1',
          productDescription: null,
          extractedImgId: 'dd5ae3b0-4fe4-43bb-a8f1-e78b870c4d02',
          extractedImgVersion: 62,
          pageNo: 'page-9',
          type: 'image',
          prespectiveName: '',
          pageId: 'bee986dc-8ad1-4ae7-9b9c-9319e3d8e1da',
          hotspotDetails: [
            {
              hotspotString: '1',
              hotspotCoords: [
                [537, 106],
                [600, 180],
              ],
              partId: null,
              partDescription: null,
              qty: 0,
            },
            {
              hotspotString: '2',
              hotspotCoords: [
                [872, 1930],
                [941, 2007],
              ],
              partId: null,
              partDescription: null,
              qty: 0,
            },
          ],
          svgHeader:
            '<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="3947" height="2176"><image width="3947" height="2176" xlink:href="./page-9_ORDER-1_svgfile.png?"></image>',
          svgFileName: 'page-9_ORDER-1_svgfile.svg',
          svgFileId: null,
          assemblyIdRef: '',
        },
      ],
      tableList: [
        {
          pageName: 'Page No. 9',
          pageNo: 'page-9',
          type: 'table',
          pageId: 'bee986dc-8ad1-4ae7-9b9c-9319e3d8e1da',
          tableId: 'bee986dc-8ad1-4ae7-9b9c-9319e3d8e1da_1',
          order: 1,
          tableNameAsInPDF: '2_Gusset',
          tableName: 'Table No. 1',
          tables: [
            {
              tableId: 'bee986dc-8ad1-4ae7-9b9c-9319e3d8e1da_1',
              tableNameAsInPDF: '2_Gusset',
              tableName: 'Table No. 1',
              isAccepted: true,
              order: 1,
              tableData: [
                ['*right hand', 'left hand', 'Unnamed: 2', 'Unnamed: 3'],
                ['36 (914.4)', 'D-AP115-3615', 'D-AP115-3616', 'D-AP115-3613'],
                ['44 (1117.6)', 'D-AP115-4404', 'D-AP115-4405', 'D-AP115-4402'],
                ['48 (1219.2)', 'D-AP115-4804', 'D-AP115-4805', 'D-AP115-4802'],
                ['54 (1371.6)', 'D-AP115-5404', 'D-AP115-5405', 'D-AP115-5402'],
                ['60 (1524)', 'D-AP115-5404', 'D-AP115-6005', 'D-AP115-6002'],
                ['66 (1676.4)', 'D-AP115-6610', 'D-AP115-6610', 'D-AP115-6002'],
              ]
            }
          ]
        }
      ]
    }
  }
};
