export const IMAGES = [
  {
    drawingName: 'page-7_ORDER-1',
    extractedImgId: '383f29a1-a8cc-4b79-a35b-cbc5f6f2b255',
    type: 'image',
  },
  {
    drawingName: 'Hardware Assembly Drawing',
    extractedImgId: 'img-hw-001',
    type: 'image',
  },
  {
    drawingName: 'Fastener Details',
    extractedImgId: 'img-fast-001',
    type: 'image',
  },
  {
    drawingName: 'Bolt Technical Drawing',
    extractedImgId: 'img-bolt-001',
    type: 'image',
  },
  {
    drawingName: 'Electrical Schematic',
    extractedImgId: 'img-elec-001',
    type: 'image',
  },
  {
    drawingName: 'Wiring Diagram',
    extractedImgId: 'img-wire-001',
    type: 'image',
  },
  {
    drawingName: 'Connector Pinout',
    extractedImgId: 'img-conn-001',
    type: 'image',
  },
  {
    drawingName: 'page-8_ORDER-1',
    extractedImgId: '7287b7ed-cd5b-420d-b9bd-5ddc6de2bd31',
    type: 'image',
  },
  {
    drawingName: 'Seal Cross-Section',
    extractedImgId: 'img-seal-001',
    type: 'image',
  },
  {
    drawingName: 'page-9_ORDER-1',
    extractedImgId: '5bd4f35c-3b43-47d4-b69a-d7027eba5455',
    type: 'image',
  },
  {
    drawingName: 'Panel Layout',
    extractedImgId: 'img-panel-001',
    type: 'image',
  },
  {
    drawingName: 'Door Assembly',
    extractedImgId: 'img-door-001',
    type: 'image',
  },
  {
    drawingName: 'page-9_ORDER-2',
    extractedImgId: 'b1572339-79e7-4ef7-b095-7d0b54daa06c',
    type: 'image',
  },
  {
    drawingName: 'Compression Spring Drawing',
    extractedImgId: 'img-comp-spring-001',
    type: 'image',
  },
];

export const TABLES = [
  {
    tables: [
      {
        isAccepted: true,
        tableId: 'f9c645dc-d482-4985-a000-1ba1613b0059_1',
        tableData: [
          ['Sequence', 'Part Id', 'Description', 'Qty'],
          ['0', 'ARK-80190', 'RING,ANVIL,CRUSHER,80-19', '-'],
          ['0', 'ARK-80200', 'RING,ANVIL,CRUSHER,80-20', '-'],
          ['0', 'ARK-80210', 'RING,ANVIL,CRUSHER,80-21', '-'],
          ['1', 'ARW-80000', 'RING,CAP,ANVIL,80,WELD', '1'],
          ['2', '08-00130', 'HOSE,HYD,GATES,3201-1104,300PS', '210"'],
          ['3', 'ANV-80009', 'ANVIL WEDGE 80', '19, 20 or 21'],
          ['4', 'ANV-80000', 'ANVIL,80', '19, 20 or 21'],
          ['5', 'ANV-WP002', 'WEAR-PLATE,ANVIL,SLIP,54,70,80', '19, 20 or 21'],
        ],
        tableName: 'Table No. 1',
        order: 1,
      },
    ],
    pageNo: 'page-9',
    type: 'table',
    pageId: 'f9c645dc-d482-4985-a000-1ba1613b0059',
    pageName: 'Page No. 9',
  },
  {
    tables: [
      {
        isAccepted: true,
        tableId: 'a115fe71-29bd-45e6-9792-124400b04cdf_1',
        tableData: [
          ['Sequence', 'Part Id', 'Description', 'Qty'],
          ['1', '03-05446', 'NUT,LCK,BRG,AN24', '2'],
          ['2', '03-05448', 'WSR,LCK,BRG,W24', '1'],
          ['3', 'HUB-80000', 'HUB,80/96,W/PIN', '1'],
          ['4', 'KEY-11214', 'KEYSTOCK,3/4X3/4X1-3/4', '1'],
          ['5', 'PDK-81000', 'PEDESTAL,80,V-TWIN,ASSY', '1'],
          ['6', '13-00439', 'BLT,HEX,1-8X4,GR8', '12'],
          ['7', '13-04364', 'WSR,FLT,SAE,1,THRU-HARD,YZ', '12'],
          ['8', 'KEY', 'KEY FOR SHEAVE,8/8V15.0,QDJ,MTO', '1'],
          ['9', '02-02766', 'BSH,0400,QDJ', '1'],
          ['10', '06-01996', 'SHEAVE,8/8V15.0,QDJ,MTO', '1'],
          ['11', '13-06779', 'PIN,DOWEL,3/4X2', '3'],
          ['12', '13-06775', 'BLT,HEX,1-8X2-3/4,GR8, YZ', '6'],
          ['13', '13-04364', 'WSR,FLT,SAE,1,THRU-HARD,YZ', '6'],
        ],
        tableName: 'Table No. 1',
        order: 1,
      },
    ],
    pageNo: 'page-11',
    type: 'table',
    pageId: 'a115fe71-29bd-45e6-9792-124400b04cdf',
    pageName: 'Page No. 11',
  },
  {
    tables: [
      {
        isAccepted: true,
        tableId: '2317f657-b74e-4d70-bbda-c9a6ecff5151_1',
        tableData: [
          ['Sequence', 'Part Id', 'Description', 'Qty'],
          ['0', 'STK-35-4LT', 'TABLE,SHOE,COMPLETE,35-4,', '-'],
          ['1', '13-700130', 'BLT,HEX,3/4-10X2,GR8', '1'],
          ['2', '13-11006', 'WSR,LCK,3/4,HI-ALLOY,YZ', '1'],
          ['3', '13-02163', 'WSR,FLT,SAE,3/4,THRU-HARD,YZ', '1'],
          ['4', 'FDT-35400', 'TABLE,DISC,FEED,35,4-SHOE', '1'],
          ['5', 'ISH-35381', 'SHOE,IMPELLER,35,38,LT', '4'],
          ['6', '13-06778', 'WSR,LCK,1-1/2,YZ,Hi-Alloy', '4'],
          ['7', '13-06777', 'BLT,HEX,1-1/2-6x2-1/2,GR8,BO', '4'],
          ['8', '13-06760', 'SCREW,FHSC,3/4-10x1-1/4,BO', '8'],
          ['9', 'ITL-35411', 'LINER,TABLE,RAMP,IMPELLER,35-4', '4'],
          ['10', 'EDG-35390', 'LINER,EDGE,35SC,39SC,35ST,2', '16'],
          ['11', '13-700707', 'WSR,LCK,7/8,YZ,HI-ALLOY', '32'],
          ['12', '13-02250', 'BLT,HEX,7/8-9x2,GR8,YZ', '32'],
          ['13', 'STW-35-4', 'TABLE,SHOE,BARE,35-4', '1'],
        ],
        tableName: 'Table No. 1',
        order: 1,
      },
    ],
    pageNo: 'page-13',
    type: 'table',
    pageId: '2317f657-b74e-4d70-bbda-c9a6ecff5151',
    pageName: 'Page No. 13',
  },
  {
    tables: [
      {
        isAccepted: true,
        tableId: 'ebfaddc4-3111-4a07-a2bc-9bcbd7de34bc_1',
        tableData: [
          ['Sequence', 'Part Id', 'Description', 'Qty'],
          ['1', 'FHL-80000', 'LINER, HOPPER, FEED, 80', '2'],
          ['2', 'FTL-80001', 'LINER, TUBE, FEED, 80, UPPPER, 20"P', '1'],
          ['3', 'HPW-80000', 'HOPPER, FEED, 80, WELD', '1'],
          ['4', 'FTL-80000', 'LINER, TUBE, FEED, 80', '1'],
          ['5', 'HAW-80100', 'ADJUSTER, HOPPER, UPPER, 80,', '1'],
          ['6', 'HAW-80200', 'ADJUSTER, HOPPER, LOWER, 80,', '1'],
          ['7', 'HAK-80001', 'KIT, SCREW, ADJ, HOPPER', '2'],
          ['8', '13-00037', 'NUT, ACME, 1-1/2-4, CR1018', '8'],
          ['9', '13-06763', 'BLT, EYE, 3/4-10x2, LIFTING', '1'],
          ['10', 'ILL-80000', 'LINER, LID, INNER, 80', '4'],
          ['11', 'OLL-70800', 'Outer Lid Liner 70 80', '8'],
          ['12', '13-05758', 'BLT, PLOW, 3/8-16x2, GR5, PLN', '68'],
          ['13', '13-700281', 'NUT, HEX, 3/8-16, GR8, YZ', '68'],
          ['14', '13-700265', 'WSR, LCK, 3/8, YZ, ALLOY', '68'],
          ['15', '13-703317', 'WSR, FLT, USS, 3/8, YZ, 1OD', '68'],
          ['16', 'IDW-54-96', 'BAR, SAFETY, 54/70/80/90', '1'],
          ['17', 'IDW-80000', 'DOOR, INSPECTION, 80, WELD', '1'],
          ['18', '13-06769', 'SCREW, SH, SOCKET, 1-8X4', '6'],
          ['19', '13-01088', 'NUT, JAM, 1-8', '6'],
          ['20', '13-01428', 'BLT, HEX, 1/2-13x1-1/4, GR8, ZNC, Y', '6'],
          ['21', '13-00710', 'NUT, HEX, 1/2-13, GR8, YZ', '6'],
          ['22', '13-700266', 'WSR, LCK, 1/2, YZ, HI-ALLOY', '6'],
        ],
        tableName: 'Table No. 1',
        order: 1,
      },
    ],
    pageNo: 'page-15',
    type: 'table',
    pageId: 'ebfaddc4-3111-4a07-a2bc-9bcbd7de34bc',
    pageName: 'Page No. 15',
  },
  {
    tables: [
      {
        isAccepted: true,
        tableId: '8afbdf2a-5340-4c85-93e5-74638e66c9c5_1',
        tableData: [
          ['Sequence', 'Part Id', 'Description', 'Qty'],
          ['1', '13-700097', 'BLT,HEX,3/8-16X1,GR8', '16'],
          ['2', '13-703317', 'WSR,FLT,USS,3/8,YZ,1OD', '4'],
          ['3', '13-700265', 'WSR,LCK,3/8,YZ,ALLOY', '20'],
          ['4', 'ARM-20002', 'COVER,ARM,54,70,80', '1'],
          ['5', 'LTW-80301', 'LIFT,ARM,80,WELD, W/VIB-CONT', '1'],
          ['6', 'HYD-REB25', 'BASE CLEVIS W/(2) 1/2 X 3/4 SO', '1'],
          ['7', 'HYD-RAM02', 'RC-254 (25 TON) RAM', '1'],
          ['8', 'HYD-REP25', 'PLUNGER CLEVIS', '1'],
          ['9', '03-06055', 'NUT,LCK,BRG,AN15', '1'],
          ['10', 'LTW-80101', 'LIFT,SHAFT,80,WELD,W/VIB-CONT', '1'],
          ['11', '03-06057', 'BRG,BALL,75MM,6215-2RSR-C3', '1'],
          ['12', '03-06056', 'BRG,BALL,60MM,DEEP-GRV.', '1'],
          ['13', '13-06781', 'RETAINER,RING,2-3/8,EXTERNAL', '1'],
          ['14', 'LTW-54200', 'LIFT,HOUSING,54/70/80,WELD', '1'],
          ['15', '13-700119', 'BLT,HEX,5/8-11X2-1/2,GR8,YZ', '6'],
          ['16', '13-700261', 'WSR,FLT,USS,5/8,YZ,1-3/4OD', '9'],
          ['17', '13-00882', 'WSR,LCK,5/8,YZ,HI-ALLOY', '9'],
          ['18', '13-00711', 'NUT,HEX,5/8-11,GR8,YZ', '9'],
          ['19', '13-700118', 'BLT,HEX,5/8-11X2,GR8,YZ', '3'],
          ['20', 'PIN-34801', 'PIN,PIVOT,80,', '1'],
          ['21', 'PIN-32801', 'PIN,RAM,LOWER,80/96XHD,', '1'],
          ['22', 'ARM-30001', 'DONUT,URETHANE', '10'],
          ['23', 'ARM-30902', 'COVER,PIN,RAM,UPPER&PIVOT,80,9', '4'],
          ['24', 'ARM-30901', 'COVER,PIN,RAM,LOWER,80,96XHD,', '2'],
          ['25', 'PIN-33801', 'PIN,RAM,UPPER,80,', '1'],
          ['26', 'PIN-31801', 'PIN,TUBE,LID,80/96XHD,', '2'],
          ['27', '13-00669', 'BLT,HEX,3/8-16X1-1/4,GR8', '4'],
        ],
        tableName: 'Table No. 1',
        order: 1,
      },
    ],
    pageNo: 'page-17',
    type: 'table',
    pageId: '8afbdf2a-5340-4c85-93e5-74638e66c9c5',
    pageName: 'Page No. 17',
  },
  {
    tables: [
      {
        isAccepted: true,
        tableId: 'bb4b1418-7a4b-4d85-b1a8-df68dc06b420_1',
        tableData: [
          ['Sequence', 'Part Id', 'Description', 'Qty'],
          ['1', '04-02419', 'MOTOR,300/350/400HP,1800RPM,F1', '1'],
          ['2', 'MOTOR SHAFT KEY', '1"X1"X7" KEY', '1'],
          ['3', '02-02765', 'BSH,0404,QDJ', '1'],
          ['4', '06-02001', 'SHEAVE,8/8V14.0,QDJ,6,500FPM-RATED,CAST-IRON', '1'],
          ['5', 'MMK-54960', 'KIT,SCREW,BELT-TENSION,5496XHD,PART', '1'],
          ['6', 'MMW-38001', 'MOUNT,MOTOR,200/250HP,', '1'],
          ['7', 'MMW-25400', 'WRENCH,ADJ,54-96,WELD', '1'],
          ['8', '13-700133', 'BLT,HEX,3/4-10X3-1/2,GR8', '4'],
          ['9', '13-00191', 'WSR,FLT,USS,3/4,ZINC', '4'],
          ['10', '13-00202', 'WSR,LCK,3/4', '4'],
          ['11', '13-200051', 'NUT,NYLOCK,3/4,GR5', '4'],
          ['12', '13-01428', 'BLT,HEX,1/2-13X1-1/4,GR8,ZNC,Y', '8'],
          ['13', '13-700266', 'WSR,LCK,1/2,ZINC HIGH ALLOY', '8'],
          ['14', '13-700138', 'BLT,HEX,7/8-9x3,GR8', '6'],
          ['15', '13-03969', 'WSR,FLT,USS,7/8,THRU-HARD,YZ', '6'],
          ['16', '13-700707', 'WSR,LCK,7/8,YZ,HI-ALLOY', '6'],
          ['17', '13-00526', 'NUT,HEX,7/8-9,GR8,ZNC,Y', '6'],
        ],
        tableName: 'Table No. 1',
        order: 1,
      },
    ],
    pageNo: 'page-19',
    type: 'table',
    pageId: 'bb4b1418-7a4b-4d85-b1a8-df68dc06b420',
    pageName: 'Page No. 19',
  },
  {
    tables: [
      {
        isAccepted: true,
        tableId: 'e4998e1f-a1fb-4191-a73d-cfb62fd1f118_1',
        tableData: [
          ['Sequence', 'Part Id', 'Description', 'Qty'],
          ['0', 'OIL-90005', 'LUBE,OIL,SYSTEM,1HP.W/RESERVOIR,W/FILTER', '-'],
          ['1', '08-11245', 'HYD,5406-8-4-HEX-RED-BSH', '2'],
          ['2', '08-20089', 'HYD,5605-08-08-08, FNPT,AIR-WAY', '2'],
          ['3', 'HYD-ELB27', '7/8 MORB X 1/2 MPT ELBOW 90', '1'],
          ['4', '08-00154', 'HYD,FLOWMETER,0-300GPM,ORB 1/2', '1'],
          ['5', 'OIL-00034', 'HUB L-075 X 5/8 STD 3/16 X 3/32 KW', '1'],
          ['6', '08-05638', 'HYD,6402-10-8-MO-RXFJX,CONN', '1'],
          ['7', '08-00377', 'HYD,2404-8-8-MJXMP-CONNECTOR', '2'],
          ['8', 'OIL-00002', 'FILLER CAP ASSEMBLY', '1'],
          ['9', 'OIL-00032-1', 'COVER PLATE TOP WITH HOLES', '1'],
          ['10', 'OIL-00038', 'PUMP/MOTOR MOUNT 6028', '1'],
          ['11', '13-10811', 'SCREW,SHC,3/8-16X1-1/2,A574BO', '6'],
          ['12', '13-700265', 'WSR,LCK,3/8,YZ,ALLOY', '6'],
          ['13', 'HYD-HOS44', '22" 8M3K HOSE WITH 8FJX - 8FJX FITT', '1'],
          ['14', 'OIL-00035', 'SPIDER L-075/AL-075 SOX', '1'],
          ['15', 'OIL-00036', 'HUB L-075 X 3/4 STD 3/16 X 3/32 KW', '1'],
          ['16', 'OIL-00033', 'PUMP 287X70020', '1'],
          ['17', '13-10811', 'SCREW,SHC,3/8-16X1-1/2,A574BO, SOCKET,HEAD,CAP,3/8"HEX', '6'],
          ['18', '13-700265', 'WSR,LCK,3/8,YZ,ALLOY', '8'],
          ['19', 'BKP-ELB23', '1" STREET MNPT X 1" FNPT STREET ELBOW', '2'],
          ['20', '08-20098', 'HYD,6405-16-16,MORB/PIP,', '1'],
          ['21', '08-02848', 'PIPE,NIPPLE,0104X1000-BLACK', '1'],
          ['22', '08-00165', 'FILTER,HYD,HEAD,3/4"NPT,P561134,DONALDSON', '1'],
          ['23', '13-700100', 'BLT,HEX,3/8-16X2,GR8,YZ', '4'],
          ['24', '13-703317', 'WSR,FLT,USS,3/8,YZ,1OD', '4'],
          ['25', 'OIL-00031-1', 'COVER PLATE ROCK PROTECTOR', '1'],
          ['26', 'OIL-00020', '160 PSI PRESSURE GAUGE 213.53 2-1/2', '1'],
          ['27', '08-11243', 'HYD,5404-12-08-MP-HEX-NIPPLE', '1'],
          ['28', '13-00038', 'BLT,HEX,1/4-20X3/4,GR5,ZINC', '2'],
          ['29', '13-700263', 'WSR,LCK,1/4,YZ,HI-ALLOY', '4'],
          ['30', '08-00212', 'HYD,ASY,FILTER,10 MICRON,HYDAC,15GPM', '1'],
          ['31', '08-00020', 'HYD,304-C-8-JIC,CAP-NUT,NUT,CAP,FEMALE,JIC', '1'],
          ['32', '08-00378', 'HYD,2404-8-12-MJXMP-CONNECTOR', '1'],
          ['33', '08-717556', 'HYD,FILTER,1"-12UNC,10MICRON', '1'],
          ['34', '11-06799', 'ELBOW,CONDUIT,90DEG,ACCESSPORT,3/4", ALUMINUM', '1'],
          ['35', 'BKP-BSH39', 'BUSHING,REDUCER,Z,1/2,3/4"', '1'],
          ['36', 'BKP-NIP04', '1/2 CLOSE NIPPLE', '1'],
          ['37', 'BKP-BSH37-M', 'BUSHING,PIPE,NPT,DOUBLE,1,1/2,', '1'],
          ['38', '08-00022', 'HYD,304-C-12-JIC,CAP-NUT,NUT,CAP,FEMALE,JIC', '1'],
          ['39', '13-06772', 'PIPE,NIPPLE,1/4-18X1/4-18,', '1'],
          ['40', 'BKP-CUP02', '1/4 PIPE COUPLING', '2'],
          ['41', '08-00131', 'SWITCH,TEMP/FLOAT,86F-164F,1/4NPT,50WATT', '1'],
          ['42', '08-11234', 'HYD,5404-8-8-MP-HEX-NIPPLE', '1'],
          ['43', '08-00568', 'HYD,2501-8-8-MJXMP90', '1'],
          ['44', '08-703135', 'HYD,ADAPTER,5404-8-6,PIPE', '1'],
          ['45', '08-00150', 'HYD,VALVE,CHECK,65PSI,8GPM', '1'],
          ['46', '08-00111', 'HYD,6405-10-8,MORB/PIPE', '1'],
          ['47', 'OIL-00057', 'GASKET,CHANNEL,RESEVOIR', '1'],
          ['48', '08-00110', 'SIGHTGLASS,TANK,M12X1.75', '1'],
          ['49', 'PRT-034', 'VALVE,GATE,1/2"', '1'],
          ['50', 'BKP-PLG11', '2" SQUARE HEAD PLUG CORED BLACK', '1'],
          ['51', '04-02415', 'MOTOR,001.0HP,1760RPM,', '1'],
          ['52', '08-00577', 'HYD,2501-12-12-MJXMP90', '1'],
        ],
        tableName: 'Table No. 1',
        order: 1,
      },
    ],
    pageNo: 'page-21',
    type: 'table',
    pageId: 'e4998e1f-a1fb-4191-a73d-cfb62fd1f118',
    pageName: 'Page No. 21',
  },
  {
    tables: [
      {
        isAccepted: true,
        tableId: 'f85a0183-5c22-4b67-8aee-c05628ad222d_1',
        tableData: [
          ['Sequence', 'Part Id', 'Description', 'Qty'],
          ['1', '03-05446', 'NUT,LCK,BRG,AN24', '4'],
          ['2', '03-05448', 'WSR,LCK,BRG,W24', '2'],
          ['3', '51-00515', 'SEAL,OIL,6.0X7.506X0.5,CRWHA1', '1'],
          ['4', '13-01431', 'SCREW,SHC,1/2-13X1-1/2,A574BO', '6'],
          ['5', 'TSP-80961', 'PLATE,SEAL,TOP,80,96', '1'],
          ['6', '08-05249', 'O-RING,-273,9-3/4"IDX1/8"W', '2'],
          ['7', 'PDK-81000-01', 'KEY,3/4X3/4X1.75', '1'],
          ['8', 'SFT-81000', 'SHAFT,MAIN,V-TWIN,80,TURBO', '1'],
          ['9', 'PDK-81000-02', 'KEY,1X1X7', '1'],
          ['10', '03-06060', 'BRG,130MM,23226-E1A-XL-M-C3,NON-TAPERED,FAG,', '1'],
          ['11', '13-06791', 'PIN,DOWEL,1/4X3/8', '1'],
          ['12', 'MMC-13501', 'TUBE,ALIGNMENT,35-96,NOT-XHD', '2'],
          ['13', '08-05455', 'O-RING,3/8"IDX1/2"ODX1/16"W,2-012-V75', '2'],
          ['14', 'PED-80000', 'HOUSING,PEDESTAL,80/96,PLG', '1'],
          ['15', '03-06062', 'BRG,110MM,22322-E1A-XL-K-M-C3,TAPERED-BORE', '1'],
          ['16', 'BSP-81000', 'PLATE,SEAL,BOTTM,80-V-TWIN', '1'],
          ['17', '51-00513', 'SEAL,OIL,4X4.999X.438', '1'],
          ['18', '13-00098', 'BLT,HEX,1/2-13X2,GR5', '6'],
          ['19', '13-00200', 'WSR,LCK,1/2', '6'],
          ['20', '08-00168', 'HYD,2503-8-6,MJICXMNPTF', '1'],
          ['21', '08-704322', 'HYD,2503-12-12,PIPE,JIC,45DEG', '1'],
          ['22', '08-00175', 'HYD,BIF-352-04-02,FIFXMNPT45', '1'],
        ],
        tableName: 'Table No. 1',
        order: 1,
      },
    ],
    pageNo: 'page-23',
    type: 'table',
    pageId: 'f85a0183-5c22-4b67-8aee-c05628ad222d',
    pageName: 'Page No. 23',
  },
  {
    tables: [
      {
        isAccepted: true,
        tableId: 'fe07caf1-b11e-4d52-80ae-a26210492a3a_1',
        tableData: [
          ['Sequence', 'Part Id', 'Description', 'Qty'],
          ['1', 'TCW-80000', 'TUB-CHANNEL,WELD,80,', '1'],
          ['2', 'PSW-80000', 'SHROUD,PEDESTAL,80/96,WELD', '1'],
          ['3', '13-700117', 'BLT,HEX,5/8-11X1-1/2,GR8', '4'],
          ['4', '13-00882', 'WSR,LCK,5/8,HI-ALLOY,YZ', '4'],
          ['5', 'MMF-12EYE-1P', '3/4" LID EYE NUT/WASHER PAINTE,RED, CEMCO', '6'],
          ['6', 'MMF-12680P', '3/4 X 8-3/4 LID LOCK EYEBOLT,PAINTED, RED, CEMCO', '6'],
          ['7', 'ZCS-35960P', 'CASTING,CAMLOCK,PAINTED', '6'],
          ['8', '13-00695', 'BLT,HEX,3/4-10X5,GR8,ZNC,HEX,CAP,SCREW', '6'],
          ['9', '13-00590', 'NUT,HEX,3/4-10,GR8,YZ', '12'],
          ['10', '08-00121', 'SEAL,RUBBER, 3/4"', '213in'],
          ['11', 'BGW-80001', 'GUARD,BELT,DRIVE,SINGLE,WELD,CHASSIS,80', '1'],
          ['12', 'CHW-80001', 'CHUTE,2-SET,70/80,WELD', '2'],
          ['13', '13-00676', 'BLT,HEX,1/2-13X1,GR8', '24'],
          ['14', '13-700266', 'WSR,LCK,1/2,ZINC HIGH ALLOY', '128'],
          ['15', '13-00710', 'NUT,HEX,1/2-13,GR8', '128'],
          ['16', '13-00066', 'BLT,HEX,3/8-16X1-1/2,GR5,ZNC', '6'],
          ['17', '13-00187', 'WSR,FLT,USS,3/8', '6'],
          ['18', '13-00198', 'WSR,LCK,3/8', '6'],
          ['19', '13-06795', 'BLT,PLOW,1/2-13X2-1/4,GR5,PLN', '80'],
          ['20', '13-03967', 'WSR,FLT,USS,1/2,THRU-HARD,YZ', '104'],
          ['21', 'UTL-80000-K2', 'LINER,TUB,UPPER, HC25,T-80', '24'],
          ['22', 'LTL-80000', 'LINER,TUB,LOWER,80', '16'],
          ['23', 'CHA-80000', 'LINER,CHANNEL,CENTER,80', '12'],
          ['24', '13-06793', 'BLT,PLOW,1/2-13X1-3/4,GR5,PLN', '24'],
          ['25', '13-03912', 'BLT,PLOW,5/8-11X2-1/2,GR5,PLN', '4'],
          ['26', '13-00882', 'WSR,LCK,5/8,HI-ALLOY,YZ', '4'],
          ['27', '13-00711', 'NUT,HEX,5/8-11,GR8,YZ', '4'],
          ['28', 'BOS-24000', 'BOSS,2-15/16 OD,C-314B', '4'],
          ['29', 'TSL-80000', 'LINER,TUB,SUPPORT,80', '2'],
        ],
        tableName: 'Table No. 1',
        order: 1,
      },
    ],
    pageNo: 'page-25',
    type: 'table',
    pageId: 'fe07caf1-b11e-4d52-80ae-a26210492a3a',
    pageName: 'Page No. 25',
  },
  {
    tables: [
      {
        isAccepted: true,
        tableId: '7acf5904-4911-4301-ad62-ce41728638cb_1',
        tableData: [
          ['Sequence', 'Part Id', 'Description', 'Qty'],
          ['1', '08-00378', 'HYD,2404-8-12-MJXMP-CONNECTOR', '1'],
          ['2', '08-00112', 'PIPE,4311-8-8,BARBXMJIC,BRASS,PUSH,ON', '2'],
          ['3', '08-00134', 'HOSE,HYD,GATES3201-1102,300PSI', '1'],
          ['4', 'HYD-ELB10', '3/4 MJIC X 1/2 MNPT X 90Í', '1'],
          ['5', '08-00577', 'HYD,2501-12-12-MJXMP90', '2'],
          ['6', '08-00113', 'PIPE,4311-12-12,BARBXFMJIC,BRA,PUSH,ON', '2'],
          ['7', '08-00130', 'HOSE,HYD,GATES,3201-1104,300PS', '1'],
        ],
        tableName: 'Table No. 1',
        order: 1,
      },
    ],
    pageNo: 'page-26',
    type: 'table',
    pageId: '7acf5904-4911-4301-ad62-ce41728638cb',
    pageName: 'Page No. 26',
  },
  {
    tables: [
      {
        isAccepted: true,
        tableId: '02883595-52ee-4e48-a03f-8982e2f725e4_1',
        tableData: [
          ['Sequence', 'Part Id', 'Description', 'Qty'],
          ['1', '08-00020', 'HYD,304-C-8-JIC,CAP-NUT', '1'],
          ['2', '08-00022', 'HYD,304-C-12-JIC,CAP-NUT', '1'],
          ['3', '08-00568', 'HYD,2501-8-8-MJXMP90', '2'],
          ['4', '08-00577', 'HYD,2501-12-12-MJXMP90', '2'],
          ['5', '08-00377', 'HYD,2404-8-8-MJXMP-CONNECTOR', '1'],
          ['6', '08-00387', 'HYD,2404-12-12-MJXMP-CONNECTOR', '1'],
          ['7', '08-00112', 'PIPE,4311-8-8,BARBXMJIC,BRASS', '2'],
          ['8', '08-00113', 'PIPE,4311-12-12,BARBXFMJIC,BRA', '2'],
          ['9', '08-00134', 'HOSE,HYD,GATES3201-1102,300PSI', '1'],
          ['10', '08-00130', 'HOSE,HYD,GATES,3201-1104,300PS', '1'],
          ['11', '08-00168', 'HYD,2503-8-6,MJICXMNPTF', '1'],
          ['12', '08-704322', 'HYD,2503-12-12,PIPE,JIC,45DEG', '1'],
          ['13', '08-00175', 'HYD,BIF-352-04-02,FIFXMNPT45', '1'],
          ['14', '21-04014', 'LINE,BRAKE,1/4"', '1'],
          ['15', '08-00176', 'HYD,BIF-402-04-02,FIFXMNPT90', '1'],
          ['16', '13-00721', 'ZERK,1/8-NPT-STRAIGHT', '1'],
        ],
        tableName: 'Table No. 1',
        order: 1,
      },
    ],
    pageNo: 'page-27',
    type: 'table',
    pageId: '02883595-52ee-4e48-a03f-8982e2f725e4',
    pageName: 'Page No. 27',
  },
  {
    tables: [
      {
        isAccepted: true,
        tableId: 'b5e1f641-bd21-4476-a345-2a8269825dc1_1',
        tableData: [
          ['Sequence', 'Part Id', 'Description', 'Qty'],
          ['0', '11-06773', 'ELE-065 Assembly: ENCL,OIL,NEMA12', '-'],
          ['1', 'ELE-349', 'Amber Domed Lens', '1'],
          ['2', 'ELE-356', 'IDEC AMBER LED LAMP', '1'],
          ['3', 'ELE-328', '120V LED GREEN LAMP', '4'],
          ['4', 'ELE-325', 'GREEN DOME LENSE', '4'],
          ['5', 'ELE-364', '4-20MA DIGITAL VIBRATION READER/INDI', '1'],
          ['6', 'ELE-327', '120V LED RED LAMP', '3'],
          ['7', 'ELE-326', 'RED DOMED LENS - TWTD INC', '3'],
          ['8', '11-06810', 'SWTICH,BUTTON,PUSH,ILLUMIN', '2'],
          ['9', 'ELE-346', 'E-STOP 1-NO-1-NC', '1'],
          ['10', 'ELE-329', 'HOUR METER', '1'],
          ['11', 'ELE-364', '4-20MA DIGITAL VIBRATION READER/INDI', '1'],
          ['12', 'ELE-324', 'LIGHT BASE - SCREW PORTION FOR BULBS', '8'],
          ['13', 'ELE-366', 'IDEC SMART RELAY BASE MODULE', '1'],
          ['14', 'ELE-303', 'CONTROL TRANSFORMER W/ PRIMARY FUSE', '1'],
          ['15', 'ELE-305', 'GREY DELAY RELAY (POST-LUBE TIMER)', '1'],
          ['16', 'ELE-317', 'BGE 35AMP TERMINAL BLOCK', '4'],
          ['17', 'ELE-320', '35AMP RED TERMINAL BLOCK', '5'],
          ['18', 'ELE-319', 'BLUE TERMINAL BLOCK', '2'],
          ['19', '11-06811', 'ELEC,CONTACTOR,22A,120V,4-POLE', '3'],
          ['20', '11-06812', 'ELEC,RELAY,SOLID-STATE,4A', '3'],
        ],
        tableName: 'Table No. 1',
        order: 1,
      },
    ],
    pageNo: 'page-31',
    type: 'table',
    pageId: 'b5e1f641-bd21-4476-a345-2a8269825dc1',
    pageName: 'Page No. 31',
  },
];

// Complete dataset conforming to AssemblyHierarchyApiResponse interface
// 5 root nodes with minimum 2 levels of hierarchy
export const MOCK_ASSEMBLY_HIERARCHY: import('./types').AssemblyHierarchyApiResponse = {
  statusCode: 200,
  data: {
    assemblyHierarchy: {
      classRoot: 'INDUSTRIAL_EQUIPMENT',
      rootIds: [
        'root-hydraulic-001',
        'root-pneumatic-002',
        'root-electrical-003',
        'root-mechanical-004',
        'root-safety-005',
      ],
      nodes: {
        // ========== ROOT 1: HYDRAULIC SYSTEM ==========
        'root-hydraulic-001': {
          classRoot: 'INDUSTRIAL_EQUIPMENT',
          classCode: 'HYD',
          parentClassCode: '',
          assemblyId: 'root-hydraulic-001',
          parentAssemblyId: '',
          assemblyName: 'HYDRAULIC_SYSTEM',
          childIds: ['child-hyd-pumps-001', 'child-hyd-valves-002'],
          itemOrder: ['img-hyd-001', 'child-hyd-pumps-001', 'child-hyd-valves-002'],
          images: [
            {
              extractedImgVersion: 1,
              productId: 'PROD-HYD-001',
              pageNo: 'page-1',
              extractedImgId: 'img-hyd-001',
              imageNameAsInPDF: 'hydraulic_overview.png',
              type: 'image',
              drawingName: 'Hydraulic System Overview',
              productDescription: 'Main hydraulic system schematic',
            },
          ],
          tables: [
            {
              tables: [
                {
                  tableNameAsInPDF: 'Hydraulic Components',
                  isAccepted: true,
                  tableId: 'tab-hyd-001',
                  tableData: [
                    ['Component', 'Part No.', 'Pressure (PSI)', 'Flow (GPM)', 'Qty'],
                    ['Main Pump', 'HP-1000', '3000', '25', '1'],
                    ['Relief Valve', 'RV-500', '3500', '30', '2'],
                    ['Filter Assembly', 'FA-200', '3000', '25', '1'],
                  ],
                  tableName: 'Hydraulic Components List',
                  order: 1,
                },
              ],
              pageNo: 'page-1',
              type: 'table',
              pageId: 'page-hyd-001',
              pageName: 'Hydraulic Overview',
            },
          ],
        },
        'child-hyd-pumps-001': {
          classRoot: 'INDUSTRIAL_EQUIPMENT',
          classCode: 'HYD-PUMP',
          parentClassCode: 'HYD',
          assemblyId: 'child-hyd-pumps-001',
          parentAssemblyId: 'root-hydraulic-001',
          assemblyName: 'HYDRAULIC_PUMPS',
          childIds: ['leaf-hyd-gear-pump-001'],
          itemOrder: ['img-hyd-pump-001', 'leaf-hyd-gear-pump-001'],
          images: [
            {
              extractedImgVersion: 1,
              productId: 'PROD-HYD-002',
              pageNo: 'page-2',
              extractedImgId: 'img-hyd-pump-001',
              imageNameAsInPDF: 'pump_assembly.png',
              type: 'image',
              drawingName: 'Pump Assembly Drawing',
              productDescription: 'Hydraulic pump components',
            },
          ],
          tables: [
            {
              tables: [
                {
                  tableNameAsInPDF: 'Pump Specifications',
                  isAccepted: true,
                  tableId: 'tab-hyd-pump-001',
                  tableData: [
                    ['Model', 'Displacement (cc/rev)', 'Max RPM', 'Max Pressure (bar)', 'Weight (kg)'],
                    ['GP-100', '16', '3500', '250', '4.5'],
                    ['GP-200', '25', '3000', '300', '6.2'],
                  ],
                  tableName: 'Pump Specifications',
                  order: 1,
                },
              ],
              pageNo: 'page-2',
              type: 'table',
              pageId: 'page-hyd-pump-001',
              pageName: 'Pump Details',
            },
          ],
        },
        'leaf-hyd-gear-pump-001': {
          classRoot: 'INDUSTRIAL_EQUIPMENT',
          classCode: 'HYD-PUMP-GEAR',
          parentClassCode: 'HYD-PUMP',
          assemblyId: 'leaf-hyd-gear-pump-001',
          parentAssemblyId: 'child-hyd-pumps-001',
          assemblyName: 'GEAR_PUMP_ASSEMBLY',
          childIds: [],
          itemOrder: ['img-gear-pump-001'],
          images: [
            {
              extractedImgVersion: 1,
              productId: 'PROD-HYD-003',
              pageNo: 'page-3',
              extractedImgId: 'img-gear-pump-001',
              imageNameAsInPDF: 'gear_pump_exploded.png',
              type: 'image',
              drawingName: 'Gear Pump Exploded View',
              productDescription: 'Internal gear pump components',
            },
          ],
          tables: [
            {
              tables: [
                {
                  tableNameAsInPDF: 'Gear Pump Parts',
                  isAccepted: true,
                  tableId: 'tab-gear-pump-001',
                  tableData: [
                    ['Item', 'Part No.', 'Description', 'Material', 'Qty'],
                    ['1', 'GP-GEAR-01', 'Drive Gear', 'Hardened Steel', '1'],
                    ['2', 'GP-GEAR-02', 'Idler Gear', 'Hardened Steel', '1'],
                    ['3', 'GP-SEAL-01', 'Shaft Seal', 'Viton', '2'],
                    ['4', 'GP-BRG-01', 'Needle Bearing', 'Steel/Bronze', '4'],
                  ],
                  tableName: 'Gear Pump BOM',
                  order: 1,
                },
              ],
              pageNo: 'page-3',
              type: 'table',
              pageId: 'page-gear-pump-001',
              pageName: 'Gear Pump Parts',
            },
          ],
        },
        'child-hyd-valves-002': {
          classRoot: 'INDUSTRIAL_EQUIPMENT',
          classCode: 'HYD-VALVE',
          parentClassCode: 'HYD',
          assemblyId: 'child-hyd-valves-002',
          parentAssemblyId: 'root-hydraulic-001',
          assemblyName: 'HYDRAULIC_VALVES',
          childIds: ['leaf-hyd-directional-valve-001'],
          itemOrder: ['img-hyd-valve-001', 'leaf-hyd-directional-valve-001'],
          images: [
            {
              extractedImgVersion: 1,
              productId: 'PROD-HYD-004',
              pageNo: 'page-4',
              extractedImgId: 'img-hyd-valve-001',
              imageNameAsInPDF: 'valve_manifold.png',
              type: 'image',
              drawingName: 'Valve Manifold Assembly',
              productDescription: 'Hydraulic valve block',
            },
          ],
          tables: [
            {
              tables: [
                {
                  tableNameAsInPDF: 'Valve Specifications',
                  isAccepted: true,
                  tableId: 'tab-hyd-valve-001',
                  tableData: [
                    ['Valve Type', 'Port Size', 'Flow (L/min)', 'Pressure (bar)', 'Actuation'],
                    ['Directional 4/3', '3/8"', '60', '350', 'Solenoid'],
                    ['Check Valve', '1/4"', '30', '400', 'Spring'],
                    ['Relief Valve', '1/2"', '80', '350', 'Pilot'],
                  ],
                  tableName: 'Valve Types',
                  order: 1,
                },
              ],
              pageNo: 'page-4',
              type: 'table',
              pageId: 'page-hyd-valve-001',
              pageName: 'Valve Specifications',
            },
          ],
        },
        'leaf-hyd-directional-valve-001': {
          classRoot: 'INDUSTRIAL_EQUIPMENT',
          classCode: 'HYD-VALVE-DIR',
          parentClassCode: 'HYD-VALVE',
          assemblyId: 'leaf-hyd-directional-valve-001',
          parentAssemblyId: 'child-hyd-valves-002',
          assemblyName: 'DIRECTIONAL_CONTROL_VALVE',
          childIds: [],
          itemOrder: ['img-dir-valve-001'],
          images: [
            {
              extractedImgVersion: 1,
              productId: 'PROD-HYD-005',
              pageNo: 'page-5',
              extractedImgId: 'img-dir-valve-001',
              imageNameAsInPDF: 'directional_valve.png',
              type: 'image',
              drawingName: '4/3 Directional Valve',
              productDescription: 'Solenoid operated directional valve',
            },
          ],
          tables: [
            {
              tables: [
                {
                  tableNameAsInPDF: 'Directional Valve Parts',
                  isAccepted: true,
                  tableId: 'tab-dir-valve-001',
                  tableData: [
                    ['Item', 'Part No.', 'Description', 'Qty'],
                    ['1', 'DV-SPOOL-01', 'Valve Spool', '1'],
                    ['2', 'DV-SOL-01', 'Solenoid Coil 24VDC', '2'],
                    ['3', 'DV-SPRING-01', 'Centering Spring', '2'],
                    ['4', 'DV-SEAL-01', 'O-Ring Kit', '1'],
                  ],
                  tableName: 'Directional Valve BOM',
                  order: 1,
                },
              ],
              pageNo: 'page-5',
              type: 'table',
              pageId: 'page-dir-valve-001',
              pageName: 'Directional Valve Parts',
            },
          ],
        },

        // ========== ROOT 2: PNEUMATIC SYSTEM ==========
        'root-pneumatic-002': {
          classRoot: 'INDUSTRIAL_EQUIPMENT',
          classCode: 'PNE',
          parentClassCode: '',
          assemblyId: 'root-pneumatic-002',
          parentAssemblyId: '',
          assemblyName: 'PNEUMATIC_SYSTEM',
          childIds: ['child-pne-cylinders-001', 'child-pne-frl-002'],
          itemOrder: ['img-pne-001', 'child-pne-cylinders-001', 'child-pne-frl-002'],
          images: [
            {
              extractedImgVersion: 1,
              productId: 'PROD-PNE-001',
              pageNo: 'page-10',
              extractedImgId: 'img-pne-001',
              imageNameAsInPDF: 'pneumatic_layout.png',
              type: 'image',
              drawingName: 'Pneumatic System Layout',
              productDescription: 'Air system overview',
            },
          ],
          tables: [
            {
              tables: [
                {
                  tableNameAsInPDF: 'Pneumatic System',
                  isAccepted: true,
                  tableId: 'tab-pne-001',
                  tableData: [
                    ['Component', 'Part No.', 'Pressure (PSI)', 'Port Size', 'Qty'],
                    ['Air Compressor', 'AC-500', '150', '1"', '1'],
                    ['Air Tank', 'AT-80G', '200', '1"', '1'],
                    ['Main Regulator', 'REG-100', '150', '3/4"', '1'],
                  ],
                  tableName: 'Pneumatic Components',
                  order: 1,
                },
              ],
              pageNo: 'page-10',
              type: 'table',
              pageId: 'page-pne-001',
              pageName: 'Pneumatic Overview',
            },
          ],
        },
        'child-pne-cylinders-001': {
          classRoot: 'INDUSTRIAL_EQUIPMENT',
          classCode: 'PNE-CYL',
          parentClassCode: 'PNE',
          assemblyId: 'child-pne-cylinders-001',
          parentAssemblyId: 'root-pneumatic-002',
          assemblyName: 'PNEUMATIC_CYLINDERS',
          childIds: ['leaf-pne-double-acting-001'],
          itemOrder: ['img-pne-cyl-001', 'leaf-pne-double-acting-001'],
          images: [
            {
              extractedImgVersion: 1,
              productId: 'PROD-PNE-002',
              pageNo: 'page-11',
              extractedImgId: 'img-pne-cyl-001',
              imageNameAsInPDF: 'cylinder_types.png',
              type: 'image',
              drawingName: 'Cylinder Types',
              productDescription: 'Pneumatic cylinder variants',
            },
          ],
          tables: [
            {
              tables: [
                {
                  tableNameAsInPDF: 'Cylinder Specs',
                  isAccepted: true,
                  tableId: 'tab-pne-cyl-001',
                  tableData: [
                    ['Model', 'Bore (mm)', 'Stroke (mm)', 'Type', 'Mount'],
                    ['CYL-32-100', '32', '100', 'Double Acting', 'Clevis'],
                    ['CYL-50-200', '50', '200', 'Double Acting', 'Foot'],
                    ['CYL-25-50', '25', '50', 'Single Acting', 'Nose'],
                  ],
                  tableName: 'Cylinder Specifications',
                  order: 1,
                },
              ],
              pageNo: 'page-11',
              type: 'table',
              pageId: 'page-pne-cyl-001',
              pageName: 'Cylinder Specs',
            },
          ],
        },
        'leaf-pne-double-acting-001': {
          classRoot: 'INDUSTRIAL_EQUIPMENT',
          classCode: 'PNE-CYL-DA',
          parentClassCode: 'PNE-CYL',
          assemblyId: 'leaf-pne-double-acting-001',
          parentAssemblyId: 'child-pne-cylinders-001',
          assemblyName: 'DOUBLE_ACTING_CYLINDER',
          childIds: [],
          itemOrder: ['img-da-cyl-001'],
          images: [
            {
              extractedImgVersion: 1,
              productId: 'PROD-PNE-003',
              pageNo: 'page-12',
              extractedImgId: 'img-da-cyl-001',
              imageNameAsInPDF: 'da_cylinder_exploded.png',
              type: 'image',
              drawingName: 'Double Acting Cylinder Exploded',
              productDescription: 'Cylinder internal components',
            },
          ],
          tables: [
            {
              tables: [
                {
                  tableNameAsInPDF: 'Cylinder Parts',
                  isAccepted: true,
                  tableId: 'tab-da-cyl-001',
                  tableData: [
                    ['Item', 'Part No.', 'Description', 'Material', 'Qty'],
                    ['1', 'CYL-TUBE-01', 'Cylinder Tube', 'Aluminum', '1'],
                    ['2', 'CYL-ROD-01', 'Piston Rod', 'Chrome Steel', '1'],
                    ['3', 'CYL-PISTON-01', 'Piston', 'Aluminum', '1'],
                    ['4', 'CYL-SEAL-KIT', 'Seal Kit', 'NBR/PU', '1'],
                  ],
                  tableName: 'Cylinder BOM',
                  order: 1,
                },
              ],
              pageNo: 'page-12',
              type: 'table',
              pageId: 'page-da-cyl-001',
              pageName: 'Cylinder Parts',
            },
          ],
        },
        'child-pne-frl-002': {
          classRoot: 'INDUSTRIAL_EQUIPMENT',
          classCode: 'PNE-FRL',
          parentClassCode: 'PNE',
          assemblyId: 'child-pne-frl-002',
          parentAssemblyId: 'root-pneumatic-002',
          assemblyName: 'FRL_UNIT',
          childIds: ['leaf-pne-filter-001'],
          itemOrder: ['img-frl-001', 'leaf-pne-filter-001'],
          images: [
            {
              extractedImgVersion: 1,
              productId: 'PROD-PNE-004',
              pageNo: 'page-13',
              extractedImgId: 'img-frl-001',
              imageNameAsInPDF: 'frl_unit.png',
              type: 'image',
              drawingName: 'FRL Assembly',
              productDescription: 'Filter-Regulator-Lubricator unit',
            },
          ],
          tables: [
            {
              tables: [
                {
                  tableNameAsInPDF: 'FRL Components',
                  isAccepted: true,
                  tableId: 'tab-frl-001',
                  tableData: [
                    ['Component', 'Model', 'Port Size', 'Flow (SCFM)', 'Qty'],
                    ['Filter', 'F-200', '1/4"', '50', '1'],
                    ['Regulator', 'R-200', '1/4"', '50', '1'],
                    ['Lubricator', 'L-200', '1/4"', '50', '1'],
                  ],
                  tableName: 'FRL Components',
                  order: 1,
                },
              ],
              pageNo: 'page-13',
              type: 'table',
              pageId: 'page-frl-001',
              pageName: 'FRL Details',
            },
          ],
        },
        'leaf-pne-filter-001': {
          classRoot: 'INDUSTRIAL_EQUIPMENT',
          classCode: 'PNE-FRL-FILTER',
          parentClassCode: 'PNE-FRL',
          assemblyId: 'leaf-pne-filter-001',
          parentAssemblyId: 'child-pne-frl-002',
          assemblyName: 'AIR_FILTER',
          childIds: [],
          itemOrder: ['img-filter-001'],
          images: [
            {
              extractedImgVersion: 1,
              productId: 'PROD-PNE-005',
              pageNo: 'page-14',
              extractedImgId: 'img-filter-001',
              imageNameAsInPDF: 'air_filter.png',
              type: 'image',
              drawingName: 'Air Filter Cutaway',
              productDescription: 'Coalescing filter internals',
            },
          ],
          tables: [
            {
              tables: [
                {
                  tableNameAsInPDF: 'Filter Parts',
                  isAccepted: true,
                  tableId: 'tab-filter-001',
                  tableData: [
                    ['Item', 'Part No.', 'Description', 'Qty'],
                    ['1', 'FLT-BOWL-01', 'Filter Bowl', '1'],
                    ['2', 'FLT-ELEM-01', '5 Micron Element', '1'],
                    ['3', 'FLT-DRAIN-01', 'Auto Drain', '1'],
                  ],
                  tableName: 'Filter Parts',
                  order: 1,
                },
              ],
              pageNo: 'page-14',
              type: 'table',
              pageId: 'page-filter-001',
              pageName: 'Filter Parts',
            },
          ],
        },

        // ========== ROOT 3: ELECTRICAL SYSTEM ==========
        'root-electrical-003': {
          classRoot: 'INDUSTRIAL_EQUIPMENT',
          classCode: 'ELE',
          parentClassCode: '',
          assemblyId: 'root-electrical-003',
          parentAssemblyId: '',
          assemblyName: 'ELECTRICAL_SYSTEM',
          childIds: ['child-ele-motors-001', 'child-ele-controls-002'],
          itemOrder: ['img-ele-001', 'child-ele-motors-001', 'child-ele-controls-002'],
          images: [
            {
              extractedImgVersion: 1,
              productId: 'PROD-ELE-001',
              pageNo: 'page-20',
              extractedImgId: 'img-ele-001',
              imageNameAsInPDF: 'electrical_schematic.png',
              type: 'image',
              drawingName: 'Main Electrical Schematic',
              productDescription: 'System electrical diagram',
            },
          ],
          tables: [
            {
              tables: [
                {
                  tableNameAsInPDF: 'Electrical Summary',
                  isAccepted: true,
                  tableId: 'tab-ele-001',
                  tableData: [
                    ['Circuit', 'Voltage', 'Current (A)', 'Breaker', 'Wire Size'],
                    ['Main Power', '480V 3PH', '100', '125A', '2/0 AWG'],
                    ['Control', '120V AC', '15', '20A', '12 AWG'],
                    ['24V DC', '24V DC', '10', 'Fused', '14 AWG'],
                  ],
                  tableName: 'Electrical Summary',
                  order: 1,
                },
              ],
              pageNo: 'page-20',
              type: 'table',
              pageId: 'page-ele-001',
              pageName: 'Electrical Overview',
            },
          ],
        },
        'child-ele-motors-001': {
          classRoot: 'INDUSTRIAL_EQUIPMENT',
          classCode: 'ELE-MOT',
          parentClassCode: 'ELE',
          assemblyId: 'child-ele-motors-001',
          parentAssemblyId: 'root-electrical-003',
          assemblyName: 'ELECTRIC_MOTORS',
          childIds: ['leaf-ele-vfd-motor-001'],
          itemOrder: ['img-motor-001', 'leaf-ele-vfd-motor-001'],
          images: [
            {
              extractedImgVersion: 1,
              productId: 'PROD-ELE-002',
              pageNo: 'page-21',
              extractedImgId: 'img-motor-001',
              imageNameAsInPDF: 'motor_assembly.png',
              type: 'image',
              drawingName: 'Motor Assembly',
              productDescription: 'AC induction motor',
            },
          ],
          tables: [
            {
              tables: [
                {
                  tableNameAsInPDF: 'Motor Specs',
                  isAccepted: true,
                  tableId: 'tab-motor-001',
                  tableData: [
                    ['Motor', 'HP', 'RPM', 'Frame', 'Efficiency'],
                    ['M-001', '50', '1800', '326T', '95.4%'],
                    ['M-002', '25', '1800', '284T', '94.1%'],
                    ['M-003', '10', '1200', '256T', '91.7%'],
                  ],
                  tableName: 'Motor Specifications',
                  order: 1,
                },
              ],
              pageNo: 'page-21',
              type: 'table',
              pageId: 'page-motor-001',
              pageName: 'Motor Details',
            },
          ],
        },
        'leaf-ele-vfd-motor-001': {
          classRoot: 'INDUSTRIAL_EQUIPMENT',
          classCode: 'ELE-MOT-VFD',
          parentClassCode: 'ELE-MOT',
          assemblyId: 'leaf-ele-vfd-motor-001',
          parentAssemblyId: 'child-ele-motors-001',
          assemblyName: 'VFD_MOTOR_PACKAGE',
          childIds: [],
          itemOrder: ['img-vfd-001'],
          images: [
            {
              extractedImgVersion: 1,
              productId: 'PROD-ELE-003',
              pageNo: 'page-22',
              extractedImgId: 'img-vfd-001',
              imageNameAsInPDF: 'vfd_motor.png',
              type: 'image',
              drawingName: 'VFD Motor Package',
              productDescription: 'Variable frequency drive with motor',
            },
          ],
          tables: [
            {
              tables: [
                {
                  tableNameAsInPDF: 'VFD Settings',
                  isAccepted: true,
                  tableId: 'tab-vfd-001',
                  tableData: [
                    ['Parameter', 'Setting', 'Min', 'Max', 'Units'],
                    ['Accel Time', '10', '0.1', '600', 'sec'],
                    ['Decel Time', '10', '0.1', '600', 'sec'],
                    ['Max Frequency', '60', '0', '400', 'Hz'],
                    ['Motor Poles', '4', '2', '12', '-'],
                  ],
                  tableName: 'VFD Parameters',
                  order: 1,
                },
              ],
              pageNo: 'page-22',
              type: 'table',
              pageId: 'page-vfd-001',
              pageName: 'VFD Settings',
            },
          ],
        },
        'child-ele-controls-002': {
          classRoot: 'INDUSTRIAL_EQUIPMENT',
          classCode: 'ELE-CTRL',
          parentClassCode: 'ELE',
          assemblyId: 'child-ele-controls-002',
          parentAssemblyId: 'root-electrical-003',
          assemblyName: 'CONTROL_PANEL',
          childIds: ['leaf-ele-plc-001'],
          itemOrder: ['img-ctrl-001', 'leaf-ele-plc-001'],
          images: [
            {
              extractedImgVersion: 1,
              productId: 'PROD-ELE-004',
              pageNo: 'page-23',
              extractedImgId: 'img-ctrl-001',
              imageNameAsInPDF: 'control_panel.png',
              type: 'image',
              drawingName: 'Control Panel Layout',
              productDescription: 'Main control enclosure',
            },
          ],
          tables: [
            {
              tables: [
                {
                  tableNameAsInPDF: 'Panel Components',
                  isAccepted: true,
                  tableId: 'tab-ctrl-001',
                  tableData: [
                    ['Item', 'Description', 'Manufacturer', 'Part No.', 'Qty'],
                    ['1', 'PLC CPU', 'Allen-Bradley', '1769-L33ER', '1'],
                    ['2', 'HMI 10"', 'Allen-Bradley', '2711P-T10C22D8S', '1'],
                    ['3', 'Power Supply 24V', 'Phoenix', 'QUINT-PS/1AC/24DC/20', '1'],
                  ],
                  tableName: 'Panel BOM',
                  order: 1,
                },
              ],
              pageNo: 'page-23',
              type: 'table',
              pageId: 'page-ctrl-001',
              pageName: 'Panel Components',
            },
          ],
        },
        'leaf-ele-plc-001': {
          classRoot: 'INDUSTRIAL_EQUIPMENT',
          classCode: 'ELE-CTRL-PLC',
          parentClassCode: 'ELE-CTRL',
          assemblyId: 'leaf-ele-plc-001',
          parentAssemblyId: 'child-ele-controls-002',
          assemblyName: 'PLC_SYSTEM',
          childIds: [],
          itemOrder: ['img-plc-001'],
          images: [
            {
              extractedImgVersion: 1,
              productId: 'PROD-ELE-005',
              pageNo: 'page-24',
              extractedImgId: 'img-plc-001',
              imageNameAsInPDF: 'plc_rack.png',
              type: 'image',
              drawingName: 'PLC Rack Configuration',
              productDescription: 'PLC modules and I/O',
            },
          ],
          tables: [
            {
              tables: [
                {
                  tableNameAsInPDF: 'I/O Allocation',
                  isAccepted: true,
                  tableId: 'tab-plc-001',
                  tableData: [
                    ['Module', 'Type', 'Points', 'Address', 'Description'],
                    ['Slot 1', 'DI 16pt', '16', 'I:1', 'Digital Inputs'],
                    ['Slot 2', 'DO 16pt', '16', 'O:2', 'Digital Outputs'],
                    ['Slot 3', 'AI 8ch', '8', 'I:3', 'Analog Inputs'],
                    ['Slot 4', 'AO 4ch', '4', 'O:4', 'Analog Outputs'],
                  ],
                  tableName: 'I/O Configuration',
                  order: 1,
                },
              ],
              pageNo: 'page-24',
              type: 'table',
              pageId: 'page-plc-001',
              pageName: 'PLC I/O',
            },
          ],
        },

        // ========== ROOT 4: MECHANICAL SYSTEM ==========
        'root-mechanical-004': {
          classRoot: 'INDUSTRIAL_EQUIPMENT',
          classCode: 'MECH',
          parentClassCode: '',
          assemblyId: 'root-mechanical-004',
          parentAssemblyId: '',
          assemblyName: 'MECHANICAL_SYSTEM',
          childIds: ['child-mech-bearings-001', 'child-mech-gears-002'],
          itemOrder: ['img-mech-001', 'child-mech-bearings-001', 'child-mech-gears-002'],
          images: [
            {
              extractedImgVersion: 1,
              productId: 'PROD-MECH-001',
              pageNo: 'page-30',
              extractedImgId: 'img-mech-001',
              imageNameAsInPDF: 'mechanical_overview.png',
              type: 'image',
              drawingName: 'Mechanical Assembly Overview',
              productDescription: 'Main mechanical components',
            },
          ],
          tables: [
            {
              tables: [
                {
                  tableNameAsInPDF: 'Mechanical Components',
                  isAccepted: true,
                  tableId: 'tab-mech-001',
                  tableData: [
                    ['Assembly', 'Part No.', 'Description', 'Weight (kg)', 'Qty'],
                    ['Gearbox', 'GB-500', 'Helical Gearbox 50:1', '125', '1'],
                    ['Coupling', 'CP-100', 'Flexible Jaw Coupling', '8.5', '2'],
                    ['Shaft', 'SH-200', 'Main Drive Shaft', '45', '1'],
                  ],
                  tableName: 'Mechanical Assembly List',
                  order: 1,
                },
              ],
              pageNo: 'page-30',
              type: 'table',
              pageId: 'page-mech-001',
              pageName: 'Mechanical Overview',
            },
          ],
        },
        'child-mech-bearings-001': {
          classRoot: 'INDUSTRIAL_EQUIPMENT',
          classCode: 'MECH-BRG',
          parentClassCode: 'MECH',
          assemblyId: 'child-mech-bearings-001',
          parentAssemblyId: 'root-mechanical-004',
          assemblyName: 'BEARING_ASSEMBLIES',
          childIds: ['leaf-mech-roller-bearing-001'],
          itemOrder: ['img-brg-001', 'leaf-mech-roller-bearing-001'],
          images: [
            {
              extractedImgVersion: 1,
              productId: 'PROD-MECH-002',
              pageNo: 'page-31',
              extractedImgId: 'img-brg-001',
              imageNameAsInPDF: 'bearing_types.png',
              type: 'image',
              drawingName: 'Bearing Types',
              productDescription: 'Various bearing configurations',
            },
          ],
          tables: [
            {
              tables: [
                {
                  tableNameAsInPDF: 'Bearing Specs',
                  isAccepted: true,
                  tableId: 'tab-brg-001',
                  tableData: [
                    ['Bearing', 'Type', 'Bore (mm)', 'OD (mm)', 'Load Rating (kN)'],
                    ['6210-2RS', 'Deep Groove Ball', '50', '90', '35.1'],
                    ['22210E', 'Spherical Roller', '50', '90', '95'],
                    ['32210', 'Tapered Roller', '50', '90', '87'],
                  ],
                  tableName: 'Bearing Specifications',
                  order: 1,
                },
              ],
              pageNo: 'page-31',
              type: 'table',
              pageId: 'page-brg-001',
              pageName: 'Bearing Details',
            },
          ],
        },
        'leaf-mech-roller-bearing-001': {
          classRoot: 'INDUSTRIAL_EQUIPMENT',
          classCode: 'MECH-BRG-ROLLER',
          parentClassCode: 'MECH-BRG',
          assemblyId: 'leaf-mech-roller-bearing-001',
          parentAssemblyId: 'child-mech-bearings-001',
          assemblyName: 'SPHERICAL_ROLLER_BEARING',
          childIds: [],
          itemOrder: ['img-roller-brg-001'],
          images: [
            {
              extractedImgVersion: 1,
              productId: 'PROD-MECH-003',
              pageNo: 'page-32',
              extractedImgId: 'img-roller-brg-001',
              imageNameAsInPDF: 'roller_bearing.png',
              type: 'image',
              drawingName: 'Spherical Roller Bearing',
              productDescription: 'Self-aligning roller bearing',
            },
          ],
          tables: [
            {
              tables: [
                {
                  tableNameAsInPDF: 'Roller Bearing Details',
                  isAccepted: true,
                  tableId: 'tab-roller-brg-001',
                  tableData: [
                    ['Specification', 'Value', 'Unit'],
                    ['Dynamic Load Rating', '95', 'kN'],
                    ['Static Load Rating', '80', 'kN'],
                    ['Limiting Speed', '7500', 'RPM'],
                    ['Weight', '0.65', 'kg'],
                  ],
                  tableName: 'Bearing Data',
                  order: 1,
                },
              ],
              pageNo: 'page-32',
              type: 'table',
              pageId: 'page-roller-brg-001',
              pageName: 'Roller Bearing',
            },
          ],
        },
        'child-mech-gears-002': {
          classRoot: 'INDUSTRIAL_EQUIPMENT',
          classCode: 'MECH-GEAR',
          parentClassCode: 'MECH',
          assemblyId: 'child-mech-gears-002',
          parentAssemblyId: 'root-mechanical-004',
          assemblyName: 'GEAR_ASSEMBLIES',
          childIds: ['leaf-mech-helical-gear-001'],
          itemOrder: ['img-gear-001', 'leaf-mech-helical-gear-001'],
          images: [
            {
              extractedImgVersion: 1,
              productId: 'PROD-MECH-004',
              pageNo: 'page-33',
              extractedImgId: 'img-gear-001',
              imageNameAsInPDF: 'gear_assembly.png',
              type: 'image',
              drawingName: 'Gear Train Assembly',
              productDescription: 'Gear mesh configuration',
            },
          ],
          tables: [
            {
              tables: [
                {
                  tableNameAsInPDF: 'Gear Set',
                  isAccepted: true,
                  tableId: 'tab-gear-001',
                  tableData: [
                    ['Gear', 'Teeth', 'Module', 'PCD (mm)', 'Face Width (mm)'],
                    ['Pinion', '18', '4', '72', '40'],
                    ['Gear 1', '72', '4', '288', '40'],
                    ['Gear 2', '54', '4', '216', '40'],
                  ],
                  tableName: 'Gear Dimensions',
                  order: 1,
                },
              ],
              pageNo: 'page-33',
              type: 'table',
              pageId: 'page-gear-001',
              pageName: 'Gear Details',
            },
          ],
        },
        'leaf-mech-helical-gear-001': {
          classRoot: 'INDUSTRIAL_EQUIPMENT',
          classCode: 'MECH-GEAR-HELICAL',
          parentClassCode: 'MECH-GEAR',
          assemblyId: 'leaf-mech-helical-gear-001',
          parentAssemblyId: 'child-mech-gears-002',
          assemblyName: 'HELICAL_GEAR_SET',
          childIds: [],
          itemOrder: ['img-helical-001'],
          images: [
            {
              extractedImgVersion: 1,
              productId: 'PROD-MECH-005',
              pageNo: 'page-34',
              extractedImgId: 'img-helical-001',
              imageNameAsInPDF: 'helical_gear.png',
              type: 'image',
              drawingName: 'Helical Gear Detail',
              productDescription: 'Right-hand helix gear',
            },
          ],
          tables: [
            {
              tables: [
                {
                  tableNameAsInPDF: 'Helical Gear Specs',
                  isAccepted: true,
                  tableId: 'tab-helical-001',
                  tableData: [
                    ['Property', 'Pinion', 'Gear', 'Unit'],
                    ['Helix Angle', '20', '20', 'deg'],
                    ['Normal Module', '4', '4', 'mm'],
                    ['Pressure Angle', '20', '20', 'deg'],
                    ['Hand of Helix', 'RH', 'LH', '-'],
                  ],
                  tableName: 'Helical Gear Data',
                  order: 1,
                },
              ],
              pageNo: 'page-34',
              type: 'table',
              pageId: 'page-helical-001',
              pageName: 'Helical Gear',
            },
          ],
        },

        // ========== ROOT 5: SAFETY SYSTEM ==========
        'root-safety-005': {
          classRoot: 'INDUSTRIAL_EQUIPMENT',
          classCode: 'SAFE',
          parentClassCode: '',
          assemblyId: 'root-safety-005',
          parentAssemblyId: '',
          assemblyName: 'SAFETY_SYSTEM',
          childIds: ['child-safe-guards-001', 'child-safe-sensors-002'],
          itemOrder: ['img-safe-001', 'child-safe-guards-001', 'child-safe-sensors-002'],
          images: [
            {
              extractedImgVersion: 1,
              productId: 'PROD-SAFE-001',
              pageNo: 'page-40',
              extractedImgId: 'img-safe-001',
              imageNameAsInPDF: 'safety_overview.png',
              type: 'image',
              drawingName: 'Safety System Overview',
              productDescription: 'Machine safety layout',
            },
          ],
          tables: [
            {
              tables: [
                {
                  tableNameAsInPDF: 'Safety Components',
                  isAccepted: true,
                  tableId: 'tab-safe-001',
                  tableData: [
                    ['Component', 'Part No.', 'Category', 'SIL Level', 'Qty'],
                    ['Safety Relay', 'SR-100', 'Control', 'SIL 3', '1'],
                    ['E-Stop', 'ES-RED', 'Actuator', 'SIL 2', '4'],
                    ['Light Curtain', 'LC-400', 'Sensor', 'SIL 3', '2'],
                  ],
                  tableName: 'Safety Equipment List',
                  order: 1,
                },
              ],
              pageNo: 'page-40',
              type: 'table',
              pageId: 'page-safe-001',
              pageName: 'Safety Overview',
            },
          ],
        },
        'child-safe-guards-001': {
          classRoot: 'INDUSTRIAL_EQUIPMENT',
          classCode: 'SAFE-GUARD',
          parentClassCode: 'SAFE',
          assemblyId: 'child-safe-guards-001',
          parentAssemblyId: 'root-safety-005',
          assemblyName: 'MACHINE_GUARDS',
          childIds: ['leaf-safe-interlock-001'],
          itemOrder: ['img-guard-001', 'leaf-safe-interlock-001'],
          images: [
            {
              extractedImgVersion: 1,
              productId: 'PROD-SAFE-002',
              pageNo: 'page-41',
              extractedImgId: 'img-guard-001',
              imageNameAsInPDF: 'guard_assembly.png',
              type: 'image',
              drawingName: 'Guard Assembly',
              productDescription: 'Perimeter guarding system',
            },
          ],
          tables: [
            {
              tables: [
                {
                  tableNameAsInPDF: 'Guard Specs',
                  isAccepted: true,
                  tableId: 'tab-guard-001',
                  tableData: [
                    ['Guard Type', 'Size (mm)', 'Material', 'Mesh Size', 'Qty'],
                    ['Perimeter Panel', '2000x1200', 'Steel', '50x50', '12'],
                    ['Access Gate', '1000x2000', 'Steel', '25x25', '2'],
                    ['Fixed Guard', '500x500', 'Polycarbonate', 'Solid', '4'],
                  ],
                  tableName: 'Guard Specifications',
                  order: 1,
                },
              ],
              pageNo: 'page-41',
              type: 'table',
              pageId: 'page-guard-001',
              pageName: 'Guard Details',
            },
          ],
        },
        'leaf-safe-interlock-001': {
          classRoot: 'INDUSTRIAL_EQUIPMENT',
          classCode: 'SAFE-GUARD-LOCK',
          parentClassCode: 'SAFE-GUARD',
          assemblyId: 'leaf-safe-interlock-001',
          parentAssemblyId: 'child-safe-guards-001',
          assemblyName: 'SAFETY_INTERLOCK',
          childIds: [],
          itemOrder: ['img-interlock-001'],
          images: [
            {
              extractedImgVersion: 1,
              productId: 'PROD-SAFE-003',
              pageNo: 'page-42',
              extractedImgId: 'img-interlock-001',
              imageNameAsInPDF: 'interlock_switch.png',
              type: 'image',
              drawingName: 'Interlock Switch Detail',
              productDescription: 'Guard locking interlock',
            },
          ],
          tables: [
            {
              tables: [
                {
                  tableNameAsInPDF: 'Interlock Data',
                  isAccepted: true,
                  tableId: 'tab-interlock-001',
                  tableData: [
                    ['Property', 'Value', 'Unit'],
                    ['Contact Configuration', '2NC + 1NO', '-'],
                    ['Locking Force', '2000', 'N'],
                    ['IP Rating', 'IP67', '-'],
                    ['Operating Temp', '-25 to +80', '°C'],
                  ],
                  tableName: 'Interlock Specs',
                  order: 1,
                },
              ],
              pageNo: 'page-42',
              type: 'table',
              pageId: 'page-interlock-001',
              pageName: 'Interlock',
            },
          ],
        },
        'child-safe-sensors-002': {
          classRoot: 'INDUSTRIAL_EQUIPMENT',
          classCode: 'SAFE-SENSOR',
          parentClassCode: 'SAFE',
          assemblyId: 'child-safe-sensors-002',
          parentAssemblyId: 'root-safety-005',
          assemblyName: 'SAFETY_SENSORS',
          childIds: ['leaf-safe-light-curtain-001'],
          itemOrder: ['img-sensor-001', 'leaf-safe-light-curtain-001'],
          images: [
            {
              extractedImgVersion: 1,
              productId: 'PROD-SAFE-004',
              pageNo: 'page-43',
              extractedImgId: 'img-sensor-001',
              imageNameAsInPDF: 'safety_sensors.png',
              type: 'image',
              drawingName: 'Safety Sensor Array',
              productDescription: 'Various safety sensing devices',
            },
          ],
          tables: [
            {
              tables: [
                {
                  tableNameAsInPDF: 'Sensor List',
                  isAccepted: true,
                  tableId: 'tab-sensor-001',
                  tableData: [
                    ['Sensor Type', 'Model', 'Range', 'Response Time', 'Qty'],
                    ['Light Curtain', 'LC-400', '0-4m', '14ms', '2'],
                    ['Safety Scanner', 'SS-200', '0-5.5m', '80ms', '1'],
                    ['Safety Mat', 'SM-600', '600x400mm', '20ms', '2'],
                  ],
                  tableName: 'Safety Sensors',
                  order: 1,
                },
              ],
              pageNo: 'page-43',
              type: 'table',
              pageId: 'page-sensor-001',
              pageName: 'Sensor Details',
            },
          ],
        },
        'leaf-safe-light-curtain-001': {
          classRoot: 'INDUSTRIAL_EQUIPMENT',
          classCode: 'SAFE-SENSOR-LC',
          parentClassCode: 'SAFE-SENSOR',
          assemblyId: 'leaf-safe-light-curtain-001',
          parentAssemblyId: 'child-safe-sensors-002',
          assemblyName: 'LIGHT_CURTAIN',
          childIds: [],
          itemOrder: ['img-lc-001'],
          images: [
            {
              extractedImgVersion: 1,
              productId: 'PROD-SAFE-005',
              pageNo: 'page-44',
              extractedImgId: 'img-lc-001',
              imageNameAsInPDF: 'light_curtain.png',
              type: 'image',
              drawingName: 'Light Curtain Installation',
              productDescription: 'Type 4 light curtain pair',
            },
          ],
          tables: [
            {
              tables: [
                {
                  tableNameAsInPDF: 'Light Curtain Specs',
                  isAccepted: true,
                  tableId: 'tab-lc-001',
                  tableData: [
                    ['Specification', 'Transmitter', 'Receiver', 'Unit'],
                    ['Height', '400', '400', 'mm'],
                    ['Resolution', '14', '14', 'mm'],
                    ['Current Draw', '150', '100', 'mA'],
                    ['Beam Count', '28', '28', '-'],
                  ],
                  tableName: 'Light Curtain Data',
                  order: 1,
                },
              ],
              pageNo: 'page-44',
              type: 'table',
              pageId: 'page-lc-001',
              pageName: 'Light Curtain',
            },
          ],
        },
      },
      tableList: TABLES as any,
      imageList: IMAGES as any,
    },
  },
};

export const DATA = {
  rootIds: [
    'fa930973-0287-40d8-96e4-e849fc50caff',
    '277b621d-4d34-42ac-bd9e-02d96b078402',
    '1652b17f-215b-4900-8fa5-30e537c32fe4',
    'b8810a2a-9cc1-4cc9-bf42-e62f15a96d35',
  ],
  nodes: {
    'fa930973-0287-40d8-96e4-e849fc50caff': {
      assemblyId: 'fa930973-0287-40d8-96e4-e849fc50caff',
      assemblyName: 'MOTOR_OVERVIEW',
      itemOrder: [
        '383f29a1-a8cc-4b79-a35b-cbc5f6f2b255',
        '355e0d23-1371-4848-85f9-b6bcc7583f0a',
        '9a7f3c45-2b1d-4e89-a5c3-d8f2e6b9c4a1',
        'page-7-tab-1',
      ],
      childIds: ['355e0d23-1371-4848-85f9-b6bcc7583f0a', '9a7f3c45-2b1d-4e89-a5c3-d8f2e6b9c4a1'],
      images: [
        {
          drawingName: 'page-7_ORDER-1',
          extractedImgId: '383f29a1-a8cc-4b79-a35b-cbc5f6f2b255',
          type: 'image',
        },
      ],
      tables: [
        {
          isAccepted: true,
          tableId: 'page-7-tab-1',
          tableData: [
            ['Part No.', 'Description', 'Quantity', 'Material', 'Weight (kg)'],
            ['MT-001', 'Motor Housing', '1', 'Aluminum Alloy', '2.5'],
            ['MT-002', 'Rotor Assembly', '1', 'Steel', '3.2'],
            ['MT-003', 'Stator Coil', '2', 'Copper', '1.8'],
            ['MT-004', 'Bearing Set', '2', 'Ceramic', '0.3'],
          ],
          tableName: 'Motor Specifications',
          order: 1,
        },
      ],
    },
    '355e0d23-1371-4848-85f9-b6bcc7583f0a': {
      assemblyId: '355e0d23-1371-4848-85f9-b6bcc7583f0a',
      assemblyName: 'HARDWARE',
      itemOrder: ['img-hw-001', 'c8d9e2a1-5f6b-4c3d-9e8a-1b2c3d4e5f6a', 'page-7-tab-2'],
      childIds: ['c8d9e2a1-5f6b-4c3d-9e8a-1b2c3d4e5f6a'],
      images: [
        {
          drawingName: 'Hardware Assembly Drawing',
          extractedImgId: 'img-hw-001',
          type: 'image',
        },
      ],
      tables: [
        {
          isAccepted: true,
          tableId: 'page-7-tab-2',
          tableData: [
            ['Item', 'Part Number', 'Description', 'Qty', 'Unit Price'],
            ['1', 'HW-101', 'M8 Bolt', '12', '$0.25'],
            ['2', 'HW-102', 'M8 Nut', '12', '$0.15'],
            ['3', 'HW-103', 'Washer', '24', '$0.05'],
            ['4', 'HW-104', 'Lock Washer', '12', '$0.08'],
          ],
          tableName: 'Hardware Bill of Materials',
          order: 2,
        },
      ],
    },
    'c8d9e2a1-5f6b-4c3d-9e8a-1b2c3d4e5f6a': {
      assemblyId: 'c8d9e2a1-5f6b-4c3d-9e8a-1b2c3d4e5f6a',
      assemblyName: 'FASTENERS',
      itemOrder: ['img-fast-001', '2e4a6c8d-9f1b-4a3c-8e7d-5b6a9c1d2e3f', 'tab-fast-001'],
      childIds: ['2e4a6c8d-9f1b-4a3c-8e7d-5b6a9c1d2e3f'],
      images: [
        {
          drawingName: 'Fastener Details',
          extractedImgId: 'img-fast-001',
          type: 'image',
        },
      ],
      tables: [
        {
          isAccepted: true,
          tableId: 'tab-fast-001',
          tableData: [
            ['Type', 'Size', 'Grade', 'Finish', 'Torque (Nm)'],
            ['Hex Bolt', 'M8x20', '8.8', 'Zinc Plated', '25'],
            ['Hex Bolt', 'M10x25', '10.9', 'Black Oxide', '50'],
            ['Socket Cap', 'M6x16', '12.9', 'Stainless', '12'],
            ['Set Screw', 'M5x12', '8.8', 'Plain', '8'],
          ],
          tableName: 'Fastener Specifications',
          order: 3,
        },
      ],
    },
    '2e4a6c8d-9f1b-4a3c-8e7d-5b6a9c1d2e3f': {
      assemblyId: '2e4a6c8d-9f1b-4a3c-8e7d-5b6a9c1d2e3f',
      assemblyName: 'BOLTS',
      itemOrder: ['img-bolt-001', 'tab-bolt-001', 'tab-bolt-002'],
      childIds: [],
      images: [
        {
          drawingName: 'Bolt Technical Drawing',
          extractedImgId: 'img-bolt-001',
          type: 'image',
        },
      ],
      tables: [
        {
          isAccepted: true,
          tableId: 'tab-bolt-001',
          tableData: [
            ['Size', 'Length (mm)', 'Thread Pitch', 'Head Height', 'Diameter'],
            ['M8', '20', '1.25', '5.3', '8.0'],
            ['M10', '25', '1.5', '6.4', '10.0'],
            ['M12', '30', '1.75', '7.5', '12.0'],
            ['M16', '40', '2.0', '10.0', '16.0'],
          ],
          tableName: 'Bolt Dimensions',
          order: 4,
        },
        {
          isAccepted: true,
          tableId: 'tab-bolt-002',
          tableData: [
            [
              'Grade',
              'Tensile Strength (MPa)',
              'Yield Strength (MPa)',
              'Hardness (HRC)',
              'Material',
            ],
            ['8.8', '800', '640', '22-32', 'Carbon Steel'],
            ['10.9', '1040', '940', '32-39', 'Alloy Steel'],
            ['12.9', '1220', '1100', '39-44', 'Alloy Steel'],
            ['A4-70', '700', '450', '—', 'Stainless 316'],
          ],
          tableName: 'Bolt Material Properties',
          order: 5,
        },
      ],
    },
    '9a7f3c45-2b1d-4e89-a5c3-d8f2e6b9c4a1': {
      assemblyId: '9a7f3c45-2b1d-4e89-a5c3-d8f2e6b9c4a1',
      assemblyName: 'ELECTRICAL',
      itemOrder: ['img-elec-001', '5d3c1a9b-7e2f-4b6a-9c8d-3e1f2a4b5c6d', 'tab-elec-001'],
      childIds: ['5d3c1a9b-7e2f-4b6a-9c8d-3e1f2a4b5c6d'],
      images: [
        {
          drawingName: 'Electrical Schematic',
          extractedImgId: 'img-elec-001',
          type: 'image',
        },
      ],
      tables: [
        {
          isAccepted: true,
          tableId: 'tab-elec-001',
          tableData: [
            ['Component', 'Part No.', 'Rating', 'Voltage', 'Current (A)'],
            ['Power Supply', 'PS-2000', '2kW', '220V AC', '9.1'],
            ['Motor Driver', 'MD-500', '500W', '24V DC', '20.8'],
            ['Control Board', 'CB-101', '50W', '12V DC', '4.2'],
            ['Emergency Stop', 'ES-RED', '10A', '250V AC', '10'],
          ],
          tableName: 'Electrical Components',
          order: 6,
        },
      ],
    },
    '5d3c1a9b-7e2f-4b6a-9c8d-3e1f2a4b5c6d': {
      assemblyId: '5d3c1a9b-7e2f-4b6a-9c8d-3e1f2a4b5c6d',
      assemblyName: 'WIRING',
      itemOrder: ['img-wire-001', '8b4e2f1c-6a9d-4c3e-7b5a-9d1c2e3f4a5b', 'tab-wire-001'],
      childIds: ['8b4e2f1c-6a9d-4c3e-7b5a-9d1c2e3f4a5b'],
      images: [
        {
          drawingName: 'Wiring Diagram',
          extractedImgId: 'img-wire-001',
          type: 'image',
        },
      ],
      tables: [
        {
          isAccepted: true,
          tableId: 'tab-wire-001',
          tableData: [
            ['Wire Type', 'AWG', 'Color', 'Length (m)', 'Application'],
            ['Stranded Copper', '14', 'Red', '5.0', 'Power +'],
            ['Stranded Copper', '14', 'Black', '5.0', 'Power -'],
            ['Stranded Copper', '18', 'Blue', '3.5', 'Signal'],
            ['Stranded Copper', '20', 'Green', '2.0', 'Ground'],
          ],
          tableName: 'Wire Specifications',
          order: 7,
        },
      ],
    },
    '8b4e2f1c-6a9d-4c3e-7b5a-9d1c2e3f4a5b': {
      assemblyId: '8b4e2f1c-6a9d-4c3e-7b5a-9d1c2e3f4a5b',
      assemblyName: 'CONNECTORS',
      itemOrder: ['img-conn-001', 'tab-conn-001'],
      childIds: [],
      images: [
        {
          drawingName: 'Connector Pinout',
          extractedImgId: 'img-conn-001',
          type: 'image',
        },
      ],
      tables: [
        {
          isAccepted: true,
          tableId: 'tab-conn-001',
          tableData: [
            ['Connector', 'Type', 'Pins', 'Current Rating', 'Voltage Rating'],
            ['J1', 'Molex Mini-Fit Jr', '4', '13A', '600V'],
            ['J2', 'JST-XH', '6', '3A', '250V'],
            ['J3', 'Phoenix Contact', '8', '24A', '630V'],
            ['J4', 'D-Sub 9', '9', '5A', '300V'],
          ],
          tableName: 'Connector Details',
          order: 8,
        },
      ],
    },
    '277b621d-4d34-42ac-bd9e-02d96b078402': {
      assemblyId: '277b621d-4d34-42ac-bd9e-02d96b078402',
      assemblyName: 'LINERS',
      itemOrder: [
        '7287b7ed-cd5b-420d-b9bd-5ddc6de2bd31',
        '6f8a9b1c-3d4e-5a7b-9c2d-1e3f4a5b6c7d',
        'page-8-tab-2',
      ],
      childIds: ['6f8a9b1c-3d4e-5a7b-9c2d-1e3f4a5b6c7d'],
      images: [
        {
          drawingName: 'page-8_ORDER-1',
          extractedImgId: '7287b7ed-cd5b-420d-b9bd-5ddc6de2bd31',
          type: 'image',
        },
      ],
      tables: [
        {
          isAccepted: true,
          tableId: 'page-8-tab-2',
          tableData: [
            ['Part', 'Material', 'Thickness (mm)', 'Hardness (Shore A)', 'Temperature Range'],
            ['Inner Liner', 'Nitrile Rubber', '3.0', '70', '-40°C to 100°C'],
            ['Outer Liner', 'EPDM', '2.5', '60', '-50°C to 150°C'],
            ['Seal Ring', 'Viton', '1.5', '75', '-20°C to 200°C'],
            ['Gasket', 'Silicone', '2.0', '50', '-60°C to 230°C'],
          ],
          tableName: 'Liner Materials',
          order: 9,
        },
      ],
    },
    '6f8a9b1c-3d4e-5a7b-9c2d-1e3f4a5b6c7d': {
      assemblyId: '6f8a9b1c-3d4e-5a7b-9c2d-1e3f4a5b6c7d',
      assemblyName: 'SEALS',
      itemOrder: ['img-seal-001', 'tab-seal-001'],
      childIds: [],
      images: [
        {
          drawingName: 'Seal Cross-Section',
          extractedImgId: 'img-seal-001',
          type: 'image',
        },
      ],
      tables: [
        {
          isAccepted: true,
          tableId: 'tab-seal-001',
          tableData: [
            ['Seal Type', 'Inner Dia. (mm)', 'Outer Dia. (mm)', 'Width (mm)', 'Pressure (bar)'],
            ['O-Ring', '50', '54', '2', '150'],
            ['V-Ring', '60', '70', '5', '80'],
            ['U-Cup', '45', '52', '3.5', '200'],
            ['T-Seal', '55', '62', '4', '120'],
          ],
          tableName: 'Seal Dimensions',
          order: 10,
        },
      ],
    },
    '1652b17f-215b-4900-8fa5-30e537c32fe4': {
      assemblyId: '1652b17f-215b-4900-8fa5-30e537c32fe4',
      assemblyName: 'BODY',
      itemOrder: [
        '5bd4f35c-3b43-47d4-b69a-d7027eba5455',
        '3a5b7c9d-1e2f-4a6b-8c9d-2e3f4a5b6c7d',
        'page-9-tab-1',
      ],
      childIds: ['3a5b7c9d-1e2f-4a6b-8c9d-2e3f4a5b6c7d'],
      images: [
        {
          drawingName: 'page-9_ORDER-1',
          extractedImgId: '5bd4f35c-3b43-47d4-b69a-d7027eba5455',
          type: 'image',
        },
      ],
      tables: [
        {
          isAccepted: true,
          tableId: 'page-9-tab-1',
          tableData: [
            ['Component', 'Material', 'Finish', 'Weight (kg)', 'Qty'],
            ['Main Housing', 'Cast Iron', 'Powder Coat', '15.5', '1'],
            ['Cover Plate', 'Steel', 'Zinc Plated', '2.3', '1'],
            ['Side Panel', 'Aluminum', 'Anodized', '1.8', '2'],
            ['Mounting Bracket', 'Steel', 'Black Oxide', '0.9', '4'],
          ],
          tableName: 'Body Components',
          order: 11,
        },
      ],
    },
    '3a5b7c9d-1e2f-4a6b-8c9d-2e3f4a5b6c7d': {
      assemblyId: '3a5b7c9d-1e2f-4a6b-8c9d-2e3f4a5b6c7d',
      assemblyName: 'PANELS',
      itemOrder: ['img-panel-001', '7c9e1a3b-5d6f-4a8b-9c1d-2e3f4a5b6c7d', 'tab-panel-001'],
      childIds: ['7c9e1a3b-5d6f-4a8b-9c1d-2e3f4a5b6c7d'],
      images: [
        {
          drawingName: 'Panel Layout',
          extractedImgId: 'img-panel-001',
          type: 'image',
        },
      ],
      tables: [
        {
          isAccepted: true,
          tableId: 'tab-panel-001',
          tableData: [
            ['Panel ID', 'Dimensions (mm)', 'Thickness', 'Material', 'Color'],
            ['P-001', '300x200', '2.0', 'Aluminum', 'Silver'],
            ['P-002', '250x150', '1.5', 'Steel', 'Black'],
            ['P-003', '200x100', '1.0', 'Plastic', 'Gray'],
            ['P-004', '350x250', '2.5', 'Aluminum', 'White'],
          ],
          tableName: 'Panel Specifications',
          order: 12,
        },
      ],
    },
    '7c9e1a3b-5d6f-4a8b-9c1d-2e3f4a5b6c7d': {
      assemblyId: '7c9e1a3b-5d6f-4a8b-9c1d-2e3f4a5b6c7d',
      assemblyName: 'ACCESS_DOORS',
      itemOrder: ['img-door-001', 'tab-door-001'],
      childIds: [],
      images: [
        {
          drawingName: 'Door Assembly',
          extractedImgId: 'img-door-001',
          type: 'image',
        },
      ],
      tables: [
        {
          isAccepted: true,
          tableId: 'tab-door-001',
          tableData: [
            ['Door', 'Size (mm)', 'Hinge Type', 'Lock Type', 'Weight (kg)'],
            ['Front Access', '400x300', 'Piano', 'Keyed Cam', '3.2'],
            ['Side Access', '300x200', 'Butt', 'Quarter Turn', '2.1'],
            ['Top Panel', '350x250', 'Concealed', 'Magnetic', '2.8'],
            ['Rear Service', '450x350', 'Heavy Duty', 'Padlock', '4.5'],
          ],
          tableName: 'Access Door Details',
          order: 13,
        },
      ],
    },
    'b8810a2a-9cc1-4cc9-bf42-e62f15a96d35': {
      assemblyId: 'b8810a2a-9cc1-4cc9-bf42-e62f15a96d35',
      assemblyName: 'SPRINGS',
      itemOrder: [
        'b1572339-79e7-4ef7-b095-7d0b54daa06c',
        '9d1e3f5a-7b9c-4d2e-6f8a-1c3b5d7e9f1a',
        'page-9-tab-2',
      ],
      childIds: ['9d1e3f5a-7b9c-4d2e-6f8a-1c3b5d7e9f1a'],
      images: [
        {
          drawingName: 'page-9_ORDER-2',
          extractedImgId: 'b1572339-79e7-4ef7-b095-7d0b54daa06c',
          type: 'image',
        },
      ],
      tables: [
        {
          isAccepted: true,
          tableId: 'page-9-tab-2',
          tableData: [
            ['Spring Type', 'Wire Dia. (mm)', 'OD (mm)', 'Free Length (mm)', 'Spring Rate (N/mm)'],
            ['Compression', '2.0', '20', '50', '5.2'],
            ['Extension', '1.5', '15', '40', '3.8'],
            ['Torsion', '2.5', '25', '30', '0.15'],
            ['Wave', '1.0', '18', '2.5', '12.5'],
          ],
          tableName: 'Spring Specifications',
          order: 14,
        },
      ],
    },
    '9d1e3f5a-7b9c-4d2e-6f8a-1c3b5d7e9f1a': {
      assemblyId: '9d1e3f5a-7b9c-4d2e-6f8a-1c3b5d7e9f1a',
      assemblyName: 'COMPRESSION_SPRINGS',
      itemOrder: ['img-comp-spring-001', 'tab-comp-spring-001'],
      childIds: [],
      images: [
        {
          drawingName: 'Compression Spring Drawing',
          extractedImgId: 'img-comp-spring-001',
          type: 'image',
        },
      ],
      tables: [
        {
          isAccepted: true,
          tableId: 'tab-comp-spring-001',
          tableData: [
            ['Part No.', 'Coils', 'Material', 'Load @ Compressed (N)', 'Max Deflection (mm)'],
            ['CS-101', '12', 'Music Wire', '250', '25'],
            ['CS-102', '15', 'Stainless 302', '180', '30'],
            ['CS-103', '10', 'Chrome Silicon', '320', '20'],
            ['CS-104', '18', 'Oil Tempered', '150', '35'],
          ],
          tableName: 'Compression Spring Data',
          order: 15,
        },
      ],
    },
  },
};
